<?php
/*
MarketPress Data Structures
*/

//country list
$this->countries = array(
  "AF" => "Afghanistan",
  "AL" => "Albania",
  "DZ" => "Algeria",
  "AS" => "American Samoa",
  "AD" => "Andorra",
  "AO" => "Angola",
  "AI" => "Anguilla",
  "AQ" => "Antarctica",
  "AG" => "Antigua And Barbuda",
  "AR" => "Argentina",
  "AM" => "Armenia",
  "AW" => "Aruba",
  "AU" => "Australia",
  "AT" => "Austria",
  "AZ" => "Azerbaijan",
  "BS" => "Bahamas",
  "BH" => "Bahrain",
  "BD" => "Bangladesh",
  "BB" => "Barbados",
  "BY" => "Belarus",
  "BE" => "Belgium",
  "BZ" => "Belize",
  "BJ" => "Benin",
  "BM" => "Bermuda",
  "BT" => "Bhutan",
  "BO" => "Bolivia",
  "BA" => "Bosnia And Herzegowina",
  "BW" => "Botswana",
  "BV" => "Bouvet Island",
  "BR" => "Brazil",
  "IO" => "British Indian Ocean Territory",
  "BN" => "Brunei Darussalam",
  "BG" => "Bulgaria",
  "BF" => "Burkina Faso",
  "BI" => "Burundi",
  "KH" => "Cambodia",
  "CM" => "Cameroon",
  "CA" => "Canada",
  "CV" => "Cape Verde",
  "KY" => "Cayman Islands",
  "CF" => "Central African Republic",
  "TD" => "Chad",
  "CL" => "Chile",
  "CN" => "China",
  "CX" => "Christmas Island",
  "CC" => "Cocos (Keeling) Islands",
  "CO" => "Colombia",
  "KM" => "Comoros",
  "CG" => "Congo",
  "CD" => "Congo, The Democratic Republic Of The",
  "CK" => "Cook Islands",
  "CR" => "Costa Rica",
  "CI" => "Cote D'Ivoire",
  "HR" => "Croatia (Local Name: Hrvatska)",
  "CU" => "Cuba",
  "CY" => "Cyprus",
  "CZ" => "Czech Republic",
  "DK" => "Denmark",
  "DJ" => "Djibouti",
  "DM" => "Dominica",
  "DO" => "Dominican Republic",
  "TP" => "East Timor",
  "EC" => "Ecuador",
  "EG" => "Egypt",
  "SV" => "El Salvador",
  "GQ" => "Equatorial Guinea",
  "ER" => "Eritrea",
  "EE" => "Estonia",
  "ET" => "Ethiopia",
  "FK" => "Falkland Islands (Malvinas)",
  "FO" => "Faroe Islands",
  "FJ" => "Fiji",
  "FI" => "Finland",
  "FR" => "France",
  "FX" => "France, Metropolitan",
  "GF" => "French Guiana",
  "PF" => "French Polynesia",
  "TF" => "French Southern Territories",
  "GA" => "Gabon",
  "GM" => "Gambia",
  "GE" => "Georgia",
  "DE" => "Germany",
  "GH" => "Ghana",
  "GI" => "Gibraltar",
  "GR" => "Greece",
  "GL" => "Greenland",
  "GD" => "Grenada",
  "GP" => "Guadeloupe",
  "GU" => "Guam",
  "GT" => "Guatemala",
  "GN" => "Guinea",
  "GW" => "Guinea-Bissau",
  "GY" => "Guyana",
  "HT" => "Haiti",
  "HM" => "Heard And Mc Donald Islands",
  "VA" => "Holy See (Vatican City State)",
  "HN" => "Honduras",
  "HK" => "Hong Kong",
  "HU" => "Hungary",
  "IS" => "Iceland",
  "IN" => "India",
  "ID" => "Indonesia",
  "IR" => "Iran (Islamic Republic Of)",
  "IQ" => "Iraq",
  "IE" => "Ireland",
  "IL" => "Israel",
  "IT" => "Italy",
  "JM" => "Jamaica",
  "JP" => "Japan",
  "JO" => "Jordan",
  "KZ" => "Kazakhstan",
  "KE" => "Kenya",
  "KI" => "Kiribati",
  "KP" => "Korea, Democratic People's Republic Of",
  "KR" => "Korea, Republic Of",
  "KW" => "Kuwait",
  "KG" => "Kyrgyzstan",
  "LA" => "Lao People's Democratic Republic",
  "LV" => "Latvia",
  "LB" => "Lebanon",
  "LS" => "Lesotho",
  "LR" => "Liberia",
  "LY" => "Libyan Arab Jamahiriya",
  "LI" => "Liechtenstein",
  "LT" => "Lithuania",
  "LU" => "Luxembourg",
  "MO" => "Macau",
  "MK" => "Macedonia, Former Yugoslav Republic Of",
  "MG" => "Madagascar",
  "MW" => "Malawi",
  "MY" => "Malaysia",
  "MV" => "Maldives",
  "ML" => "Mali",
  "MT" => "Malta",
  "MH" => "Marshall Islands",
  "MQ" => "Martinique",
  "MR" => "Mauritania",
  "MU" => "Mauritius",
  "YT" => "Mayotte",
  "MX" => "Mexico",
  "FM" => "Micronesia, Federated States Of",
  "MD" => "Moldova, Republic Of",
  "MC" => "Monaco",
  "MN" => "Mongolia",
  "MS" => "Montserrat",
  "MA" => "Morocco",
  "MZ" => "Mozambique",
  "MM" => "Myanmar",
  "NA" => "Namibia",
  "NR" => "Nauru",
  "NP" => "Nepal",
  "NL" => "Netherlands",
  "AN" => "Netherlands Antilles",
  "NC" => "New Caledonia",
  "NZ" => "New Zealand",
  "NI" => "Nicaragua",
  "NE" => "Niger",
  "NG" => "Nigeria",
  "NU" => "Niue",
  "NF" => "Norfolk Island",
  "MP" => "Northern Mariana Islands",
  "NO" => "Norway",
  "OM" => "Oman",
  "PK" => "Pakistan",
  "PW" => "Palau",
  "PA" => "Panama",
  "PG" => "Papua New Guinea",
  "PY" => "Paraguay",
  "PE" => "Peru",
  "PH" => "Philippines",
  "PN" => "Pitcairn",
  "PL" => "Poland",
  "PT" => "Portugal",
  "PR" => "Puerto Rico",
  "QA" => "Qatar",
  "RE" => "Reunion",
  "RO" => "Romania",
  "RU" => "Russian Federation",
  "RW" => "Rwanda",
  "KN" => "Saint Kitts And Nevis",
  "LC" => "Saint Lucia",
  "VC" => "Saint Vincent And The Grenadines",
  "WS" => "Samoa",
  "SM" => "San Marino",
  "ST" => "Sao Tome And Principe",
  "SA" => "Saudi Arabia",
  "SN" => "Senegal",
  "SC" => "Seychelles",
  "SL" => "Sierra Leone",
  "SG" => "Singapore",
  "SK" => "Slovakia (Slovak Republic)",
  "SI" => "Slovenia",
  "SB" => "Solomon Islands",
  "SO" => "Somalia",
  "ZA" => "South Africa",
  "GS" => "South Georgia, South Sandwich Islands",
  "ES" => "Spain",
  "LK" => "Sri Lanka",
  "SH" => "St. Helena",
  "PM" => "St. Pierre And Miquelon",
  "SD" => "Sudan",
  "SR" => "Suriname",
  "SJ" => "Svalbard And Jan Mayen Islands",
  "SZ" => "Swaziland",
  "SE" => "Sweden",
  "CH" => "Switzerland",
  "SY" => "Syrian Arab Republic",
  "TW" => "Taiwan",
  "TJ" => "Tajikistan",
  "TZ" => "Tanzania, United Republic Of",
  "TH" => "Thailand",
  "TG" => "Togo",
  "TK" => "Tokelau",
  "TO" => "Tonga",
  "TT" => "Trinidad And Tobago",
  "TN" => "Tunisia",
  "TR" => "Turkey",
  "TM" => "Turkmenistan",
  "TC" => "Turks And Caicos Islands",
  "TV" => "Tuvalu",
  "UG" => "Uganda",
  "UA" => "Ukraine",
  "AE" => "United Arab Emirates",
  "GB" => "United Kingdom",
  "US" => "United States",
  "UM" => "United States Minor Outlying Islands",
  "UY" => "Uruguay",
  "UZ" => "Uzbekistan",
  "VU" => "Vanuatu",
  "VE" => "Venezuela",
  "VN" => "Viet Nam",
  "VG" => "Virgin Islands (British)",
  "VI" => "Virgin Islands (U.S.)",
  "WF" => "Wallis And Futuna Islands",
  "EH" => "Western Sahara",
  "YE" => "Yemen",
  "YU" => "Yugoslavia",
  "ZM" => "Zambia",
  "ZW" => "Zimbabwe"
);

//USA states list
$this->usa_states = array(
  'AL'=>"Alabama",
	'AK'=>"Alaska",
	'AZ'=>"Arizona",
	'AR'=>"Arkansas",
	'CA'=>"California",
	'CO'=>"Colorado",
	'CT'=>"Connecticut",
	'DE'=>"Delaware",
	'DC'=>"District Of Columbia",
	'FL'=>"Florida",
	'GA'=>"Georgia",
	'HI'=>"Hawaii",
	'ID'=>"Idaho",
	'IL'=>"Illinois",
	'IN'=>"Indiana",
	'IA'=>"Iowa",
	'KS'=>"Kansas",
	'KY'=>"Kentucky",
	'LA'=>"Louisiana",
	'ME'=>"Maine",
	'MD'=>"Maryland",
	'MA'=>"Massachusetts",
	'MI'=>"Michigan",
	'MN'=>"Minnesota",
	'MS'=>"Mississippi",
	'MO'=>"Missouri",
	'MT'=>"Montana",
	'NE'=>"Nebraska",
	'NV'=>"Nevada",
	'NH'=>"New Hampshire",
	'NJ'=>"New Jersey",
	'NM'=>"New Mexico",
	'NY'=>"New York",
	'NC'=>"North Carolina",
	'ND'=>"North Dakota",
	'OH'=>"Ohio",
	'OK'=>"Oklahoma",
	'OR'=>"Oregon",
	'PA'=>"Pennsylvania",
	'RI'=>"Rhode Island",
	'SC'=>"South Carolina",
	'SD'=>"South Dakota",
	'TN'=>"Tennessee",
	'TX'=>"Texas",
	'UT'=>"Utah",
	'VT'=>"Vermont",
	'VA'=>"Virginia",
	'WA'=>"Washington",
	'WV'=>"West Virginia",
	'WI'=>"Wisconsin",
	'WY'=>"Wyoming"
);

//UK counties/provinces
$this->uk_counties = array("Aberdeenshire"=>"Aberdeenshire","Angus/Forfarshire"=>"Angus/Forfarshire","Argyllshire"=>"Argyllshire",
"Ayrshire"=>"Ayrshire","Banffshire"=>"Banffshire","Bedfordshire"=>"Bedfordshire","Berkshire"=>"Berkshire",
"Berwickshire"=>"Berwickshire","Blaenau Gwent"=>"Blaenau Gwent","Bridgend"=>"Bridgend",
"Buckinghamshire"=>"Buckinghamshire","Buteshire"=>"Buteshire","Caerphilly"=>"Caerphilly","Caithness"=>"Caithness",
"Cambridgeshire"=>"Cambridgeshire","Cardiff"=>"Cardiff","Carmarthenshire"=>"Carmarthenshire",
"Ceredigion"=>"Ceredigion","Cheshire"=>"Cheshire","Clackmannanshire"=>"Clackmannanshire",
"Conwy"=>"Conwy","Cornwall"=>"Cornwall","Cromartyshire"=>"Cromartyshire","Cumbria"=>"Cumbria",
"Denbighshire"=>"Denbighshire","Derbyshire"=>"Derbyshire","Devon"=>"Devon","Dorset"=>"Dorset",
"Dumfriesshire"=>"Dumfriesshire","Dunbartonshire/Dumbartonshire"=>"Dunbartonshire/Dumbartonshire",
"Durham"=>"Durham","East Lothian/Haddingtonshire"=>"East Lothian/Haddingtonshire","Essex"=>"Essex","Fife"=>"Fife",
"Flintshire"=>"Flintshire","Gloucestershire"=>"Gloucestershire","Greater London"=>"Greater London","Greater Manchester"=>"Greater Manchester","Gwynedd"=>"Gwynedd","Hampshire"=>"Hampshire",
"Herefordshire"=>"Herefordshire","Hertfordshire"=>"Hertfordshire","Huntingdonshire"=>"Huntingdonshire",
"Inverness-shire"=>"Inverness-shire","Isle of Anglesey"=>"Isle of Anglesey","Kent"=>"Kent",
"Kincardineshire"=>"Kincardineshire","Kinross-shire"=>"Kinross-shire","Kirkcudbrightshire"=>"Kirkcudbrightshire",
"Lanarkshire"=>"Lanarkshire","Lancashire"=>"Lancashire","Leicestershire"=>"Leicestershire",
"Lincolnshire"=>"Lincolnshire","Merthyr Tydfil"=>"Merthyr Tydfil","Middlesex"=>"Middlesex",
"Midlothian/Edinburghshire"=>"Midlothian/Edinburghshire","Monmouthshire"=>"Monmouthshire",
"Morayshire"=>"Morayshire","Nairnshire"=>"Nairnshire","Neath Port Talbot"=>"Neath Port Talbot",
"Newport"=>"Newport","Norfolk"=>"Norfolk","Northamptonshire"=>"Northamptonshire",
"Northumberland"=>"Northumberland","Nottinghamshire"=>"Nottinghamshire","Orkney"=>"Orkney",
"Oxfordshire"=>"Oxfordshire","Peeblesshire"=>"Peeblesshire","Pembrokeshire"=>"Pembrokeshire",
"Perthshire"=>"Perthshire","Powys"=>"Powys","Renfrewshire"=>"Renfrewshire",
"Rhondda Cynon Taff"=>"Rhondda Cynon Taff","Ross-shire"=>"Ross-shire","Roxburghshire"=>"Roxburghshire",
"Rutland"=>"Rutland","Selkirkshire"=>"Selkirkshire","Shetland"=>"Shetland","Shropshire"=>"Shropshire",
"Somerset"=>"Somerset","Staffordshire"=>"Staffordshire","Stirlingshire"=>"Stirlingshire","Suffolk"=>"Suffolk",
"Surrey"=>"Surrey","Sussex"=>"Sussex","Sutherland"=>"Sutherland","Swansea"=>"Swansea","Torfaen"=>"Torfaen",
"Vale of Glamorgan"=>"Vale of Glamorgan","Warwickshire"=>"Warwickshire",
"West Lothian/Linlithgowshire"=>"West Lothian/Linlithgowshire","Westmorland"=>"Westmorland",
"Wigtownshire"=>"Wigtownshire","Wiltshire"=>"Wiltshire",
"Worcestershire"=>"Worcestershire","Wrexham"=>"Wrexham","Yorkshire"=>"Yorkshire");

//Australian states
$this->australian_states = array(
  "NSW"=>"New South Wales",
  "VIC"=>"Victoria",
  "QLD"=>"Queensland",
  "TAS"=>"Tasmania",
  "SA"=>"South Australia",
  "WA"=>"Western Australia",
  "NT"=>"Northern Territory",
  "ACT"=>"Australian Capital Territory"
);

//Canadian provinces
$this->canadian_provinces = array(
  "BC"=>"British Columbia",
  "ON"=>"Ontario",
  "NL"=>"Newfoundland and Labrador",
  "NS"=>"Nova Scotia",
  "PE"=>"Prince Edward Island",
  "NB"=>"New Brunswick",
  "QC"=>"Quebec",
  "MB"=>"Manitoba",
  "SK"=>"Saskatchewan",
  "AB"=>"Alberta",
  "NT"=>"Northwest Territories",
  "NU"=>"Nunavut",
  "YT"=>"Yukon Territory"
);

$this->afganistan_regions = array(
  "BDS"=>"Badakhshan",
  "BDG"=>"Badghis",
  "BGL"=>"Baghlan",
  "BAL"=>"Balkh",
  "BAM"=>"Bamian",
  "FRA"=>"Farah",
  "FYB"=>"Faryab",
  "GHA"=>"Ghazni",
  "GHO"=>"Ghowr",
  "HEL"=>"Helmand",
  "HER"=>"Herat",
  "JOW"=>"Jowzjan",
  "KAB"=>"Kabul",
  "KAN"=>"Kandahar",
  "KAP"=>"Kapisa",
  "KHO"=>"Khost",
  "KNR"=>"Konar",
  "KDZ"=>"Kondoz",
  "LAG"=>"Laghman",
  "LOW"=>"Lowgar",
  "NAN"=>"Nangrahar",
  "NIM"=>"Nimruz",
  "NUR"=>"Nurestan",
  "ORU"=>"Oruzgan",
  "PIA"=>"Paktia",
  "PKA"=>"Paktika",
  "PAR"=>"Parwan",
  "SAM"=>"Samangan",
  "SAR"=>"Sar-e Pol",
  "TAK"=>"Takhar",
  "WAR"=>"Wardak",
  "ZAB"=>"Zabol",
);

$this->albania_regions = array(
  "1"=>"Berat county",
  "2"=>"Durres county",
  "3"=>"Elbasan county",
  "4"=>"Fier county",
  "5"=>"Gjirokaster county",
  "6"=>"Korce county",
  "7"=>"Kukes county",
  "8"=>"Lezhe county",
  "9"=>"Diber county",
  "10"=>"Shkoder county",
  "11"=>"Tirane county",
  "12"=>"Vlore county",
);

$this->algeria_region = array(
  "ADRAR"=>"Adrar",
  "AIN TEMOUCHENT"=>"Ain Temouchent",
  "ALGIERS"=>"Algiers",
  "ANNABA"=>"Annaba",
  "LAGHOUAT"=>"Laghouat",
  "BATNA"=>"Batna",
  "BEJAIA"=>"Bejaia",
  "BISKRA"=>"Biskra",
  "BECHAR"=>"Bechar",
  "BLIDA"=>"Blida",
  "BOUIRA"=>"Bouira",
  "CHLEF"=>"Chlef",
  "CONSTANTINE"=>"Constantine",
  "DJELFA"=>"Djelfa",
  "TAMANGHASSET"=>"Tamanghasset",
  "TEBESSA"=>"Tebessa",
  "TLEMCEN"=>"Tlemcen",
  "TIZI OUZOU"=>"Tizi Ouzou",
  "JIJEL"=>"Jijel",
  "SETIF"=>"Setif",
  "SAIDA"=>"Saida",
  "SKIKDA"=>"Skikda",
  "SIDI BEL ABBES"=>"Sidi Bel Abbes",
  "GUELMA"=>"Guelma",
  "MEDEA"=>"Medea",
  "MOSTAGANEM"=>"Mostaganem",
  "MSILA"=>"MSila",
  "ORAN"=>"Oran",
  "OUARGLA"=>"Ouargla",
  "OUM EL-BOUAGHI"=>"Oum el-Bouaghi",
  "EL BAYADH"=>"El Bayadh",
  "ILLIZI"=>"Illizi",
  "BORDJ BOU ARRERIDJ"=>"Bordj Bou Arreridj",
  "BOUMERDES"=>"Boumerdes",
  "EL TARF"=>"El Tarf",
  "TINDDOUF"=>"Tindouf",
  "TISSEMSILT"=>"Tissemsilt",
  "EL OUED"=>"El Oued",
  "KHENCHELA"=>"Khenchela",
  "SOUK AHRAS"=>"Souk Ahras",
  "MILA"=>"Mila",
  "AIN DEFLA"=>"Ain Defla",
  "NAAMA"=>"Naama",
  "GHARDAIA"=>"Ghardaia",
  "RELIZANE"=>"Relizane",
);

$this->andorra_regions = array(
  "CA"=>"Canillo",
  "EN"=>"Encamp",
  "MA"=>"La Massana",
  "OR"=>"Ordino",
  "JL"=>"Sant Julià de Lòria",
  "AN"=>"Andorra La Vella",
  "EE"=>"Escaldes Engordany",
);

$this->angola_regions = array(
  "BGO"=>"Bengo",
  "BGU"=>"Benguela",
  "BIE"=>"Bie",
  "CAB"=>"Cabinda",
  "CCU"=>"Cuando Cubango",
  "CNO"=>"Cuanza Norte",
  "CUS"=>"Cuanza Sul",
  "CNN"=>"Cunene",
  "HUA"=>"Huambo",
  "HUI"=>"Huila",
  "LUA"=>"Luanda",
  "LNO"=>"Lunda Norte",
  "LSU"=>"Lunda Sul",
  "MAL"=>"Malanje",
  "MOX"=>"Moxico",
  "NAM"=>"Namibe",
  "UIG"=>"Uige",
  "ZAI"=>"Zaire",
);

$this->anguilla_regions = array(
  "BP"=>"Blowing Point",
  "EE"=>"East End",
  "GH"=>"George Hill",
  "IH"=>"Island Harbour",
  "NH"=>"North Hill",
  "NS"=>"North Side",
  "SG"=>"Sandy Ground",
  "SH"=>"Sandy Hill",
  "SO"=>"South Hill",
  "ST"=>"Stoney Ground",
  "TF"=>"The Farrington",
  "TQ"=>"The Quarter (including Rey Hill)",
  "TV"=>"The Valley (including Upper & South Valley)",
  "WE"=>"West End (including Long Bay)",
);

$this->antigua_barbuda_regions = array(
  "GE"=>"St. George",
  "JO"=>"St. John",
  "MA"=>"St. Mary",
  "PA"=>"St. Paul",
  "PE"=>"St. Peter",
  "BB"=>"Barbuda",
  "RD"=>"Redonda",
  "PH"=>"St. Philip",
);

$this->argentina_regions = array(
  "A"=>"Salta",
  "B"=>"Buenos Aires Province",
  "C"=>"Capital Federal",
  "D"=>"San Luis",
  "E"=>"Entre Ríos",
  "F"=>"La Rioja",
  "G"=>"Santiago del Estero",
  "H"=>"Chaco",
  "J"=>"San Juan",
  "K"=>"Catamarca",
  "L"=>"La Pampa",
  "M"=>"Mendoza",
  "N"=>"Misiones",
  "P"=>"Formosa",
  "Q"=>"Neuquén",
  "R"=>"Río Negro",
  "S"=>"Santa Fe",
  "T"=>"Tucumán",
  "U"=>"Chubut",
  "V"=>"Tierra del Fuego",
  "W"=>"Corrientes",
  "X"=>"Córdoba",
  "Y"=>"Jujuy",
  "Z"=>"Santa Cruz",
);

$this->armenia_regions = array(
  "AG"=>"Araqacotn",
  "AR"=>"Ararat",
  "AV"=>"Armavir",
  "ER"=>"Erevan",
  "GR"=>"Geqarkunik",
  "KT"=>"Kotayk",
  "LO"=>"Lory",
  "SH"=>"Sirak",
  "SU"=>"Syunik",
  "TV"=>"Tavus",
  "VD"=>"Vayoc Jor",
);

$this->austria_regions = array(
  "BUR"=>"Burgenland",
  "KAR"=>"Kärnten",
  "NOS"=>"Niederöesterreich",
  "OOS"=>"Oberöesterreich",
  "SAL"=>"Salzburg",
  "STE"=>"Steiermark",
  "TIR"=>"Tirol",
  "VOR"=>"Vorarlberg",
  "WIE"=>"Wien",
);

$this->ajerbaijan_regions = array(
  "ABS"=>"Absheron",
  "AGM"=>"Aghdam",
  "AGS"=>"Aghdash",
  "AGC"=>"Aghjabedi",
  "AGA"=>"Aghstafa",
  "AGU"=>"Aghsu",
  "AB"=>"Ali-Bairamly",
  "AST"=>"Astara",
  "BAB"=>"Babek",
  "BA"=>"Baku",
  "BAL"=>"Balaken",
  "BAR"=>"Barda",
  "BEY"=>"Beilagan",
  "BIL"=>"Bilasuvar",
  "DAS"=>"Dashkesan",
  "DAV"=>"Devechi",
  "FUZ"=>"Fizuli",
  "QAB"=>"Gabala",
  "GAD"=>"Gadabey",
  "QAX"=>"Gakh",
  "GA"=>"Ganja",
  "QAZ"=>"Gazakh",
  "GOR"=>"Geranboy",
  "QOB"=>"Gobustan",
  "GOY"=>"Goychay",
  "QBA"=>"Guba",
  "QBI"=>"Gubadly",
  "QUS"=>"Gusar",
  "HAC"=>"Hacuqabul",
  "IMI"=>"Imishli",
  "ISM"=>"Ismailly",
  "CAL"=>"Jalilabad",
  "CAB"=>"Jebrail",
  "CUL"=>"Julfa",
  "KAL"=>"Kelbajar",
  "XAC"=>"Khachmaz",
  "XA"=>"Khankendy",
  "XAN"=>"Khanlar",
  "XCI"=>"Khojaly",
  "XVD"=>"Khojavend",
  "XIZ"=>"Khyzy",
  "KUR"=>"Kyurdamir",
  "LAC"=>"Lachin",
  "LAN"=>"Lankaran district",
  "LA"=>"Lankaran city",
  "LER"=>"Lerik",
  "MAS"=>"Masally",
  "MI"=>"Mingechevir",
  "NA"=>"Naftalan",
  "NX"=>"Nakhchivan",
  "NEF"=>"Neftchala",
  "OGU"=>"Oghuz",
  "ORD"=>"Ordubad",
  "SAT"=>"Saatly",
  "SAB"=>"Sabirabad",
  "SAL"=>"Salyan",
  "SMX"=>"Samuh",
  "SAD"=>"Sedarak",
  "SAH"=>"Shahbuz",
  "SMI"=>"Shamakhy",
  "SKR"=>"Shamkir",
  "SAK"=>"Sheki district",
  "SA"=>"Sheki city",
  "SAR"=>"Sherur",
  "SUS"=>"Shusha district",
  "SS"=>"Shusha city",
  "SIY"=>"Siazan",
  "SM"=>"Sumgayit",
  "TAR"=>"Terter",
  "TOV"=>"Tovuz",
  "UCA"=>"Ujar",
  "YAR"=>"Yardymly",
  "YEV"=>"Yevlakh district",
  "YE"=>"Yevlakh city",
  "ZAQ"=>"Zagatala",
  "ZAN"=>"Zangilan",
  "ZAR"=>"Zerdab",
);

$this->bahamas_regions = array(
  "AC"=>"Acklins and Crooked Islands",
  "BI"=>"Bimini",
  "CI"=>"Cat Island",
  "EX"=>"Exuma",
  "FP"=>"Freeport",
  "FC"=>"Fresh Creek",
  "GH', "Governor's Harbour"),
  "GT"=>"Green Turtle Cay",
  "HI"=>"Harbour Island",
  "HR"=>"High Rock",
  "IN"=>"Inaqua",
  "KB"=>"Kemps Bay",
  "LI"=>"Long Island",
  "MH"=>"Marsh Harbour",
  "MG"=>"Mayaquana",
  "NP"=>"New Providence",
  "NB"=>"Nicholls Town and Berry Islands",
  "RI"=>"Ragged Island",
  "RS"=>"Rock Sound",
  "SR"=>"San Salvador and Rum Cay",
  "SP"=>"Sandy Point",
);

$this->bahrain_regions = array(
  "BH-13"=>"Al Manamah",
  "BH-14"=>"Al Janubiyah",
  "BH-15"=>"Al Muharraq",
  "BH-16"=>"Al Wusta",
  "BH-17"=>"Ash Shamaliyah",
);

$this->bangladesh_regions = array(
  "1"=>"Barisal",
  "2"=>"Chittagong",
  "3"=>"Dhaka",
  "4"=>"Khulna",
  "5"=>"Rajshahi",
  "6"=>"Sylhet",
);

$this->barbados_regions = array(
  "01"=>"Christ Church",
  "02"=>"Saint Andrew",
  "03"=>"Saint George",
  "04"=>"Saint James",
  "05"=>"Saint John",
  "06"=>"Saint Joseph",
  "07"=>"Saint Lucy",
  "08"=>"Saint Michael",
  "09"=>"Saint Peter",
  "10"=>"Saint Philip",
  "11"=>"Saint Thomas",
);

$this->belarus_regions = array(
  "BR"=>"Brest",
  "HO"=>"Homyel",
  "HM"=>"Horad Minsk",
  "HR"=>"Hrodna",
  "MA"=>"Mahilyow",
  "MI"=>"Minsk",
  "VI"=>"Vitsyebsk",
);

$this->belgium_regions = array(
  "VWV"=>"West-Vlaanderen",
  "VOV"=>"Oost-Vlaanderen",
  "VAN"=>"Antwerpen",
  "VLI"=>"Limburg",
  "VBR"=>"Vlaams-Brabant",
  "BRU"=>"Brussel/Bruxelles",
  "WBW"=>"Brabant-Wallon",
  "WLG"=>"Liège",
  "WHT"=>"Hainaut",
  "WNA"=>"Namur",
  "WLX"=>"Luxembourg",
);

$this->belize_regions = array(
  "BZ"=>"Belize",
  "CY"=>"Cayo",
  "CZL"=>"Corozal",
  "OW"=>"Orange Walk",
  "SC"=>"Stann Creek",
  "TOL"=>"Toledo",
);

$this->benin_regions = array(
  "AL"=>"Alibori",
  "AK"=>"Atacora",
  "AQ"=>"Atlantique",
  "BO"=>"Borgou",
  "CO"=>"Collines",
  "KO"=>"Couffo",
  "DO"=>"Donga",
  "LI"=>"Littoral",
  "MO"=>"Mono",
  "OU"=>"Ouémé",
  "PL"=>"Plateau",
  "ZO"=>"Zou",
);

$this->bermuda_regions = array(
  "DEV"=>"Devonshire",
  "HAM"=>"Hamilton",
  "HA"=>"Hamilton Municipality",
  "PAG"=>"Paget",
  "PEM"=>"Pembroke",
  "SG"=>"Saint George Municipality",
  "SGE"=>"Saint Georges",
  "SAN"=>"Sandys",
  "SMI"=>"Smiths",
  "SOU"=>"Southampton",
  "WAR"=>"Warwick",
);

$this->bhutan_regions = array(
  "GA"=>"Gasa",
  "TY"=>"Tashi Yangtse",
  "11"=>"Paro",
  "12"=>"Chhukha",
  "13"=>"Ha",
  "14"=>"Samchi",
  "15"=>"Thimphu",
  "21"=>"Chirang",
  "22"=>"Daga",
  "23"=>"Punakha",
  "24"=>"Wangdi Phodrang",
  "31"=>"Geylegphug",
  "32"=>"Tongsa",
  "33"=>"Bumthang",
  "34"=>"Shemgang",
  "41"=>"Tashigang",
  "42"=>"Mongar",
  "43"=>"Pemagatsel",
  "44"=>"Lhuntshi",
  "45"=>"Samdrup Jongkhar",
);

$this->bolivia_regions = array(
  "BO-C"=>"Cochabamba",
  "BO-H"=>"Chuquisaca",
  "BO-B"=>"El Beni",
  "BO-L"=>"La Paz",
  "BO-O"=>"Oruro",
  "BO-N"=>"Pando",
  "BO-P"=>"Potosí",
  "BO-S"=>"Santa Cruz",
  "BO-T"=>"Tarija",
);

$this->bosnia_herzegoniva_regions = array(
  "BIH"=>"Federacija Bosna i Hercegovina",
  "SRP"=>"Republika Srpska",
  "05"=>"Bosansko-Podrinjski Kanton",
  "10"=>"Hercegovacko-Bosanski Kanton",
  "07"=>"Hercegovacko-Neretvanski Kanton",
  "09"=>"Kanton Sarajevo",
  "02"=>"Posavski Kanton",
  "06"=>"Srednjobosanski Kanton",
  "03"=>"Tuzlanski Kanton",
  "01"=>"Unsko-Sanski Kanton",
  "08"=>"Zapadno-Hercegovacki Kanton",
  "04"=>"Zenicko-Dobojski Kanton",
);

$this->botswana_regions = array(
  "CE"=>"Central",
  "GH"=>"Ghanzi",
  "KG"=>"Kgalagadi",
  "KL"=>"Kgatleng",
  "KW"=>"Kweneng",
  "NE"=>"North-East",
  "NW"=>"North-West",
  "SE"=>"South-East",
  "SO"=>"Southern",
);

$this->brazil_regions = array(
  "AC"=>"Acre",
  "AL"=>"Alagoas",
  "AP"=>"Amapá",
  "AM"=>"Amazonas",
  "BA"=>"Bahia",
  "CE"=>"Ceará",
  "DF"=>"Distrito Federal",
  "ES"=>"Espírito Santo",
  "GO"=>"Goiás",
  "MA"=>"Maranhão",
  "MT"=>"Mato Grosso",
  "MS"=>"Mato Grosso do Sul",
  "MG"=>"Minas Gerais",
  "PA"=>"Pará",
  "PB"=>"Paraíba",
  "PR"=>"Paraná",
  "PE"=>"Pernambuco",
  "PI"=>"Piauí",
  "RJ"=>"Rio de Janeiro",
  "RN"=>"Rio Grande do Norte",
  "RS"=>"Rio Grande do Sul",
  "RO"=>"Rondônia",
  "RR"=>"Roraima",
  "SC"=>"Santa Catarina",
  "SP"=>"São Paulo",
  "SE"=>"Sergipe",
  "TO"=>"Tocantins",
);

$this->brunei_darussalam_regions = array(
  "BN-BE"=>"Belait",
  "BN-BM"=>"Brunei-Muara",
  "BN-TE"=>"Temburong",
  "BN-TU"=>"Tutong",
);

$this->burkina_faso_regions = array(
  "BAL"=>"Bale",
  "BAM"=>"Bam",
  "BAN"=>"Banwa",
  "BAZ"=>"Bazega",
  "BGR"=>"Bougouriba",
  "BLG"=>"Boulgou",
  "BLK"=>"Boulkiemde",
  "COM"=>"Comoe",
  "GAN"=>"Ganzourgou",
  "GNA"=>"Gnagna",
  "GOU"=>"Gourma",
  "HOU"=>"Houet",
  "IOB"=>"Ioba",
  "KAD"=>"Kadiogo",
  "KEN"=>"Kenedougou",
  "KMD"=>"Komandjoari",
  "KMP"=>"Kompienga",
  "KOS"=>"Kossi",
  "KOP"=>"Koulpelogo",
  "KOT"=>"Kouritenga",
  "KOW"=>"Kourweogo",
  "LER"=>"Leraba",
  "LOR"=>"Loroum",
  "MOU"=>"Mouhoun",
  "NAO"=>"Nahouri",
  "NAM"=>"Namentenga",
  "NAY"=>"Nayala",
  "NOU"=>"Noumbiel",
  "OUB"=>"Oubritenga",
  "OUD"=>"Oudalan",
  "PAS"=>"Passore",
  "PON"=>"Poni",
  "SNG"=>"Sanguie",
  "SMT"=>"Sanmatenga",
  "SEN"=>"Seno",
  "SIS"=>"Sissili",
  "SOM"=>"Soum",
  "SOR"=>"Sourou",
  "TAP"=>"Tapoa",
  "TUI"=>"Tuy",
  "YAG"=>"Yagha",
  "YAT"=>"Yatenga",
  "ZIR"=>"Ziro",
  "ZON"=>"Zondoma",
  "ZOU"=>"Zoundweogo",
);

$this->burundi_regions = array(
  "BB"=>"Bubanza",
  "BM"=>"Bujumbura Mairie",
  "BJ"=>"Bujumbura Rural",
  "BR"=>"Bururi",
  "CA"=>"Cankuzo",
  "CI"=>"Cibitoke",
  "GI"=>"Gitega",
  "KR"=>"Karuzi",
  "KY"=>"Kayanza",
  "KI"=>"Kirundo",
  "MA"=>"Makamba",
  "MU"=>"Muramvya",
  "MY"=>"Muyinga",
  "MW"=>"Mwaro",
  "NG"=>"Ngozi",
  "RT"=>"Rutana",
  "RY"=>"Ruyigi",
);

$this->cambodia_regions = array(
  "2"=>"Baat Dambang",
  "1"=>"Banteay Mean Chey",
  "1"=>"Banteay Meanchey",
  "2"=>"Batdambang",
  "3"=>"Kampong Chaam",
  "3"=>"Kampong Cham",
  "4"=>"Kampong Chhnang",
  "5"=>"Kampong Spoe",
  "5"=>"Kampong Spueu",
  "6"=>"Kampong Thum",
  "7"=>"Kampot",
  "8"=>"Kandaal",
  "8"=>"Kandal",
  "9"=>"Kaoh Kong",
  "10"=>"Kracheh",
  "23"=>"Krong Kaeb",
  "23"=>"Krong Keb",
  "24"=>"Krong Pailin",
  "18"=>"Krong Preah Sihanouk",
  "11"=>"Mondol Kiri",
  "22"=>"Otdar Mean Chey",
  "22"=>"Otdar Meanchey",
  "12"=>"Phnom Penh",
  "12"=>"Phnum Penh",
  "15"=>"Pousaat",
  "15"=>"Pouthisat",
  "13"=>"Preah Vihear",
  "14"=>"Prey Veaeng",
  "14"=>"Prey Veng",
  "16"=>"Rotanak Kiri",
  "16"=>"Rotanokiri",
  "17"=>"Siem Reab",
  "17"=>"Siemreab",
  "19"=>"Stoeng Treng",
  "19"=>"Stueng Traeng",
  "20"=>"Svaay Rieng",
  "20"=>"Svay Rieng",
  "21"=>"Taakaev",
  "21"=>"Takev",
);

$this->cameroon_regions = array(
  "CM-AD"=>"Adamaoua",
  "CM-CE"=>"Centre",
  "CM-ES"=>"Est",
  "CM-EN"=>"Extreme-Nord",
  "CM-LT"=>"Littoral",
  "CM-NO"=>"Nord",
  "CM-NW"=>"Nord-Ouest",
  "CM-OU"=>"Ouest",
  "CM-SU"=>"Sud",
  "CM-SW"=>"Sud-Ouest",
);

$this->cape_verde_regions = array(
  "BV"=>"Boa Vista",
  "BR"=>"Brava",
  "MA"=>"Maio",
  "MO"=>"Mosteiros",
  "PA"=>"Paul",
  "PN"=>"Porto Novo",
  "PR"=>"Praia",
  "SN"=>"Ribeira Brava",
  "RG"=>"Ribeira Grande",
  "PR"=>"Ribeira Grande de Santiago",
  "SL"=>"Sal",
  "CA"=>"Santa Catarina",
  "SF"=>"Santa Catarina do Fogo",
  "CR"=>"Santa Cruz",
  "SD"=>"Sao Domingos",
  "SF"=>"Sao Filipe",
  "CR"=>"Sao Lourenço dos Orgaos",
  "CS"=>"Sao Miguel",
  "CA"=>"Sao Salvador do Mundo",
  "SV"=>"Sao Vicente",
  "TA"=>"Tarrafal",
  "TS"=>"Tarrafal de Sao Nicolau",
);

$this->caman_islands_eegions = array(
  "BT"=>"Bodden Town",
  "CB"=>"Cayman Brac",
  "EE"=>"East End",
  "GT"=>"George Town",
  "SO"=>"Little Cayman",
  "NS"=>"North Side",
  "WB"=>"West Bay",
);

$this->central_african_republic_regions = array(
  "BB"=>"Bamingui-Bangoran",
  "BGF"=>"Bangui",
  "BK"=>"Basse-Kotto",
  "HK"=>"Haute-Kotto",
  "HM"=>"Haut-Mbomou",
  "KG"=>"Kemo",
  "LB"=>"Lobaye",
  "HS"=>"Mambere-Kadei",
  "MB"=>"Mbomou",
  "KB"=>"Nana-Grebizi",
  "NM"=>"Nana-Mambere",
  "MP', "Ombella-M'Poko"),
  "UK"=>"Ouaka",
  "AC"=>"Ouham",
  "OP"=>"Ouham-Pende",
  "SE"=>"Sangha-Mbaere",
  "VK"=>"Vakaga",
);

$this->chad_regions = array(
  "KA"=>"Barh el Ghazel",
  "BA"=>"Batha",
  "BET"=>"Borkou",
  "CB"=>"Chari-Baguirmi",
  "BET"=>"Ennedi",
  "GR"=>"Guera",
  "HL"=>"Hadjer-Lamis",
  "KA"=>"Kanem",
  "LC"=>"Lac",
  "LO"=>"Logone Occidental",
  "LR"=>"Logone Oriental",
  "MA"=>"Mandoul",
  "ME"=>"Mayo-Kebbi Est",
  "MO"=>"Mayo-Kebbi Ouest",
  "MC"=>"Moyen-Chari",
  "OD"=>"Ouaddai",
  "SA"=>"Salamat",
  "OD"=>"Sila",
  "TA"=>"Tandjile",
  "BET"=>"Tibesti",
  "ND', "Ville de N'Djamena"),
  "WF"=>"Wadi Fira",
);

$this->chile_regions = array(
  "TA"=>"Tarapaca",
  "AN"=>"Antofagasta",
  "AT"=>"Atacama",
  "CO"=>"Coquimbo",
  "VA"=>"Valparaiso",
  "OH"=>"Ohiggins",
  "MA"=>"Maule",
  "BI"=>"Biobio",
  "AR"=>"Araucania",
  "LA"=>"Lagos",
  "AI"=>"Aisen",
  "MA"=>"Magallanes",
  "RM"=>"Metropolitana",
  "Ri"=>"Rios",
  "AR"=>"Arica",
);

$this->china_regions = array(
  "京"=>"北京",
  "沪"=>"上海",
  "津"=>"天津",
  "渝"=>"重庆",
  "冀"=>"河北",
  "豫"=>"河南",
  "鄂"=>"湖北",
  "湘"=>"湖南",
  "苏"=>"江苏",
  "赣"=>"江西",
  "辽"=>"辽宁",
  "吉"=>"吉林",
  "黑"=>"黑龙江",
  "陕"=>"陕西",
  "鲁"=>"山东",
  "晋"=>"山西",
  "川"=>"四川",
  "青"=>"青海",
  "皖"=>"安徽",
  "琼"=>"海南",
  "粤"=>"广东",
  "桂"=>"广西",
  "贵"=>"贵州",
  "浙"=>"浙江",
  "闽"=>"福建",
  "甘"=>"甘肃",
  "云"=>"云南",
  "蒙"=>"内蒙古",
  "宁"=>"宁夏",
  "新"=>"新疆",
  "藏"=>"西藏",
  "港"=>"香港",
  "澳"=>"澳门",
  "台"=>"台湾",
);

$this->colombia_regions = array(
  "AMA"=>"Amazonas",
  "ANT"=>"Antioquia",
  "ARA"=>"Arauca",
  "ATL"=>"Atlantico",
  "BOL"=>"Bolivar",
  "CAL"=>"Caldas",
  "CAQ"=>"Caqueta",
  "CAS"=>"Casanare",
  "CAU"=>"Cauca",
  "CES"=>"Cesar",
  "CHO"=>"Choco",
  "COR"=>"Cordoba",
  "CUN"=>"Cundinamarca",
  "DC"=>"Distrito Capital de Bogota",
  "GUA"=>"Guainia",
  "GUV"=>"Guaviare",
  "HUI"=>"Huila",
  "LAG"=>"La Guajira",
  "MAG"=>"Magdalena",
  "MET"=>"Meta",
  "NAR"=>"Narino",
  "NSA"=>"Norte de Santander",
  "PUT"=>"Putumayo",
  "QUI"=>"Quindio",
  "RIS"=>"Risaralda",
  "SAP"=>"San Andres, Providencia y Santa Catalina",
  "SAN"=>"Santander",
  "SUC"=>"Sucre",
  "TOL"=>"Tolima",
  "VAC"=>"Valle del Cauca",
  "VAU"=>"Vaupes",
  "VID"=>"Vichada",
);

$this->comoros_regions = array(
  "A"=>"Anjouan",
  "G"=>"Grande Comore",
  "M"=>"Moheli",
);

$this->congo_regions = array(
  "11"=>"Bouenza",
  "BZV"=>"Brazzaville",
  "8"=>"Cuvette",
  "15"=>"Cuvette-Ouest",
  "5"=>"Kouilou",
  "2"=>"Lekoumou",
  "7"=>"Likouala",
  "9"=>"Niari",
  "14"=>"Plateaux",
  "12"=>"Pool",
  "13"=>"Sangha",
);

$this->congo_democratic_republic_regions = array(
  "CD-KN"=>"Kinshasa",
  "CD-BN"=>"Bandundu",
  "CD-BC"=>"Bas-Congo",
  "CD-EQ"=>"Equateur",
  "CD-KW"=>"Kasai-Occidental",
  "CD-KE"=>"Kasai-Oriental",
  "CD-KA"=>"Katanga",
  "CD-MA"=>"Maniema",
  "CD-NK"=>"Nord-Kivu",
  "CD-OR"=>"Orientale",
  "CD-SK"=>"Sud-Kivu",
);

$this->costa_rica_regions = array(
  "AL"=>"Alajuela",
  "CA"=>"Cartago",
  "GU"=>"Guanacaste",
  "HE"=>"Heredia",
  "LI"=>"Limón",
  "PU"=>"Puntarenas",
  "SJ"=>"San José",
);

$this->croatia_regions = array(
  "01"=>"Zagreb county",
  "02"=>"Krapina-Zagorje county",
  "03"=>"Sisak-Moslavina county",
  "04"=>"Karlovac county",
  "05"=>"Varaždin county",
  "06"=>"Koprivnica-Križevci county",
  "07"=>"Bjelovar-Bilogora county",
  "08"=>"Primorje-Gorski Kotar county",
  "09"=>"Lika-Senj county",
  "10"=>"Virovitica-Podravina county",
  "11"=>"Požega-Slavonia county",
  "12"=>"Brod-Posavina county",
  "13"=>"Zadar county",
  "14"=>"Osijek-Baranja county",
  "15"=>"Šibenik-Knin county",
  "16"=>"Vukovar-Srijem county",
  "17"=>"Split-Dalmatia county",
  "18"=>"Istria county",
  "19"=>"Dubrovnik-Neretva county",
  "20"=>"Međimurje county",
  "21"=>"Zagreb",
);

$this->cuba_regions = array(
  "01"=>"Pinar del Rio",
  "02"=>"La Habana",
  "03"=>"Ciudad de la Habana",
  "04"=>"Matanzas",
  "05"=>"Villa Clara",
  "06"=>"Cienfuegos",
  "07"=>"Sancti Spiritus",
  "08"=>"Ciego de Avila",
  "09"=>"Camaguey",
  "10"=>"Las Tunas",
  "11"=>"Holguin",
  "12"=>"Granma",
  "13"=>"Santiago de Cuba",
  "14"=>"Sancti Spiritus",
  "99"=>"Isla de la Juventud",
);

$this->cyprus_regions = array(
  "04"=>"Famagusta",
  "06"=>"Kyrenia",
  "03"=>"Larnaca",
  "02"=>"Limassol",
  "01"=>"Nicosia",
  "05"=>"Paphos')
);

$this->czech_republic_regions = array(
  "PHA"=>"Praha",
  "STC"=>"Středočeský kraj",
  "JHC"=>"Jihočeský kraj",
  "PLK"=>"Plzeňský kraj",
  "KVK"=>"Karlovarský kraj",
  "ULK"=>"Ústecký kraj",
  "LBK"=>"Liberecký kraj",
  "HKK"=>"Královéhradecký kraj",
  "PAK"=>"Pardubický kraj",
  "VYS"=>"Vysočina",
  "JHM"=>"Jihomoravský kraj",
  "OLK"=>"Olomoucký kraj",
  "ZLK"=>"Zlínský kraj",
  "MSK"=>"Moravskoslezský kraj",
);


$this->denmark_regions = array(
  "DK-84"=>"Hovedstaden",
  "DK-82"=>"Midtjylland",
  "DK-81"=>"Nordjylland",
  "DK-85"=>"Sjælland",
  "DK-83"=>"Syddanmark",
);

$this->djibouti_regions = array(
  "AS"=>"Ali Sabieh",
  "AR"=>"Arta",
  "DI"=>"Dikhil",
  "DJ"=>"Djibouti",
  "OB"=>"Obock",
  "TA"=>"Tadjourah",
);

$this->dominica_regions = array(
  "02"=>"Saint Andrew",
  "03"=>"Saint David",
  "04"=>"Saint George",
  "05"=>"Saint John",
  "06"=>"Saint Joseph",
  "07"=>"Saint Luke",
  "08"=>"Saint Mark",
  "09"=>"Saint Patrick",
  "10"=>"Saint Paul",
  "11"=>"Saint Peter",
);

$this->dominican_republic_regions = array(
  "DN"=>"Distrito Nacional",
  "AZ"=>"Azua",
  "BC"=>"Baoruco",
  "BH"=>"Barahona",
  "DJ"=>"Dajabon",
  "DU"=>"Duarte",
  "EL"=>"Elias Pina",
  "SY"=>"El Seybo",
  "ET"=>"Espaillat",
  "HM"=>"Hato Mayor",
  "IN"=>"Independencia",
  "AL"=>"La Altagracia",
  "RO"=>"La Romana",
  "VE"=>"La Vega",
  "MT"=>"Maria Trinidad Sanchez",
  "MN"=>"Monsenor Nouel",
  "MC"=>"Monte Cristi",
  "MP"=>"Monte Plata",
  "PD"=>"Pedernales",
  "PR"=>"Peravia (Bani)",
  "PP"=>"Puerto Plata",
  "SL"=>"Salcedo",
  "SM"=>"Samana",
  "SH"=>"Sanchez Ramirez",
  "SC"=>"San Cristobal",
  "JO"=>"San Jose de Ocoa",
  "SJ"=>"San Juan",
  "PM"=>"San Pedro de Macoris",
  "SA"=>"Santiago",
  "ST"=>"Santiago Rodriguez",
  "SD"=>"Santo Domingo",
  "VA"=>"Valverde",
);

$this->ecuador_regions = array(
  "A"=>"Azuay",
  "B"=>"Bolivar",
  "F"=>"Canar",
  "C"=>"Carchi",
  "H"=>"Chimborazo",
  "X"=>"Cotopaxi",
  "O"=>"El Oro",
  "E"=>"Esmeraldas",
  "W"=>"Galapagos",
  "G"=>"Guayas",
  "I"=>"Imbabura",
  "L"=>"Loja",
  "R"=>"Los Rios",
  "M"=>"Manabi",
  "S"=>"Morona-Santiago",
  "N"=>"Napo",
  "D"=>"Orellana",
  "Y"=>"Pastaza",
  "P"=>"Pichincha",
  "U"=>"Sucumbios",
  "T"=>"Tungurahua",
  "Z"=>"Zamora-Chichipe",
);

$this->egypt_regions = array(
  "MUH"=>"مرسى مطروح",
  "ALX"=>"الاسكندرية",
  "WAD"=>"الوادي الجديد",
  "GZ"=>"الجيزة",
  "FYM"=>"الفيوم",
  "BNS"=>"بني سويف",
  "MN"=>"المنيا",
  "AST"=>"اسيوط",
  "SHG"=>"سوهاج",
  "ASN"=>"اسوان",
  "SIN"=>"شمال سيناء",
  "JS"=>"جنوب سيناء",
  "MNF"=>"المنوفية",
  "BA"=>"البحر الاحمر",
  "SHR"=>"الشرقية",
  "KB"=>"القليوبية",
  "IS"=>"الاسماعيلية",
  "SUZ"=>"السويس",
  "BH"=>"البحيرة",
  "GH"=>"الغربية",
  "KFS"=>"كفر الشيخ",
  "DK"=>"الدقهلية",
  "UQ"=>"الاقصر",
  "PTS"=>"بور سعيد",
  "DT"=>"دمياط",
  "KN"=>"قنا",
  "CAI"=>"القاهرة",
);

$this->el_salvador_regions = array(
  "AH"=>"Ahuachapan",
  "CA"=>"Cabanas",
  "CH"=>"Chalatenango",
  "CU"=>"Cuscatian",
  "LI"=>"La Libertad",
  "PA"=>"La Paz",
  "UN"=>"La Union",
  "MO"=>"Morazan",
  "SM"=>"San Miguel",
  "SS"=>"San Salvador",
  "SV"=>"San Vicente",
  "SA"=>"Santa Ana",
  "SO"=>"Sonsonate",
  "US"=>"Usulutan",
);

$this->equitorial_guinea_regions = array(
  "GQ-AN"=>"Annobon",
  "GQ-BN"=>"Bioko Norte",
  "GQ-BS"=>"Bioko Sur",
  "GQ-CS"=>"Centro Sur",
  "GQ-KN"=>"Kie-Ntem",
  "GQ-LI"=>"Litoral",
  "GQ-WN"=>"Wele-Nzas",
);

$this->eritrea_regions = array(
  "AN"=>"Anseba",
  "DU"=>"Debub",
  "DK"=>"Debubawi Keyih Bahri",
  "GB"=>"Gash Barka",
  "MA"=>"Maekel",
  "Sk"=>"Semenawi Keyih Bahri",
);

$this->estonia_regions = array(
  "37"=>"Harjumaa",
  "39"=>"Hiiumaa",
  "44"=>"Ida-Virumaa",
  "49"=>"Jõgevamaa",
  "51"=>"Järvamaa",
  "57"=>"Läänemaa",
  "59"=>"Lääne-Virumaa",
  "65"=>"Põlvamaa",
  "67"=>"Pärnumaa",
  "70"=>"Raplamaa",
  "74"=>"Saaremaa",
  "78"=>"Tartumaa",
  "82"=>"Valgamaa",
  "84"=>"Viljandimaa",
  "86"=>"Võrumaa",
);

$this->ethiopia_regions = array(
  "ET-AA"=>"Addis Ababa",
  "ET-DD"=>"Dire Dawa",
  "ET-AF"=>"Afar",
  "ET-AM"=>"Amara",
  "ET-BE"=>"Benshangul-Gumaz",
  "ET-GA"=>"Gambela Peoples",
  "ET-HA"=>"Harari People",
  "ET-OR"=>"Oromia",
  "ET-SO"=>"Somali",
  "ET-TI"=>"Tigrai",
  "ET-SN"=>"Southern Nations, Nationalities and Peoples",
);

$this->faroe_islands_regions = array(
  "NO"=>"Norderoerne",
  "OS"=>"Ostero",
  "SA"=>"Sando",
  "ST"=>"Stromo",
  "SN"=>"Sudero Nordre",
  "SS"=>"Sudero Sondre",
  "VG"=>"Vago",
);

$this->fiji_islands_regions = array(
  "BA"=>"Ba",
  "BU"=>"Bua",
  "Ck"=>"Cakaudrove",
  "KD"=>"Kadavu",
  "LU"=>"Lau",
  "LM"=>"Lomaiviti",
  "MC"=>"Macuata",
  "NN"=>"Nadroga-Navosa",
  "NT"=>"Naitasiri",
  "NM"=>"Namosi",
  "RA"=>"Ra",
  "RW"=>"Rewa",
  "RT"=>"Rotuma",
  "SR"=>"Serua",
  "TL"=>"Tailevu",
);

$this->france_regions = array(
  "FR-01"=>"Ain",
  "FR-02"=>"Aisne",
  "FR-03"=>"Allier",
  "FR-04"=>"Alpes-de-Haute-Provence",
  "FR-05"=>"Hautes-Alpes",
  "FR-06"=>"Alpes-Maritimes",
  "FR-07"=>"Ardèche",
  "FR-08"=>"Ardennes",
  "FR-09"=>"Ariège",
  "FR-10"=>"Aube",
  "FR-11"=>"Aude",
  "FR-12"=>"Aveyron",
  "FR-13"=>"Bouches-du-Rhône",
  "FR-14"=>"Calvados",
  "FR-15"=>"Cantal",
  "FR-16"=>"Charente",
  "FR-17"=>"Charente-Maritime",
  "FR-18"=>"Cher",
  "FR-19"=>"Corrèze",
  "FR-21', "Côte-d'Or"),
  "FR-22', "Côtes-d'Armor"),
  "FR-23"=>"Creuse",
  "FR-24"=>"Dordogne",
  "FR-25"=>"Doubs",
  "FR-26"=>"Drôme",
  "FR-27"=>"Eure",
  "FR-28"=>"Eure-et-Loir",
  "FR-29"=>"Finistère",
  "FR-2A"=>"Corse-du-Sud",
  "FR-2B"=>"Haute-Corse",
  "FR-30"=>"Gard",
  "FR-31"=>"Haute-Garonne",
  "FR-32"=>"Gers",
  "FR-33"=>"Gironde",
  "FR-34"=>"Hérault",
  "FR-35"=>"Ille-et-Vilaine",
  "FR-36"=>"Indre",
  "FR-37"=>"Indre-et-Loire",
  "FR-38"=>"Isère",
  "FR-39"=>"Jura",
  "FR-40"=>"Landes",
  "FR-41"=>"Loir-et-Cher",
  "FR-42"=>"Loire",
  "FR-43"=>"Haute-Loire",
  "FR-44"=>"Loire-Atlantique",
  "FR-45"=>"Loiret",
  "FR-46"=>"Lot",
  "FR-47"=>"Lot-et-Garonne",
  "FR-48"=>"Lozère",
  "FR-49"=>"Maine-et-Loire",
  "FR-50"=>"Manche",
  "FR-51"=>"Marne",
  "FR-52"=>"Haute-Marne",
  "FR-53"=>"Mayenne",
  "FR-54"=>"Meurthe-et-Moselle",
  "FR-55"=>"Meuse",
  "FR-56"=>"Morbihan",
  "FR-57"=>"Moselle",
  "FR-58"=>"Nièvre",
  "FR-59"=>"Nord",
  "FR-60"=>"Oise",
  "FR-61"=>"Orne",
  "FR-62"=>"Pas-de-Calais",
  "FR-63"=>"Puy-de-Dôme",
  "FR-64"=>"Pyrénées-Atlantiques",
  "FR-65"=>"Hautes-Pyrénées",
  "FR-66"=>"Pyrénées-Orientales",
  "FR-67"=>"Bas-Rhin",
  "FR-68"=>"Haut-Rhin",
  "FR-69"=>"Rhône",
  "FR-70"=>"Haute-Saône",
  "FR-71"=>"Saône-et-Loire",
  "FR-72"=>"Sarthe",
  "FR-73"=>"Savoie",
  "FR-74"=>"Haute-Savoie",
  "FR-75"=>"Paris",
  "FR-76"=>"Seine-Maritime",
  "FR-77"=>"Seine-et-Marne",
  "FR-78"=>"Yvelines",
  "FR-79"=>"Deux-Sèvres",
  "FR-80"=>"Somme",
  "FR-81"=>"Tarn",
  "FR-82"=>"Tarn-et-Garonne",
  "FR-83"=>"Var",
  "FR-84"=>"Vaucluse",
  "FR-85"=>"Vendée",
  "FR-86"=>"Vienne",
  "FR-87"=>"Haute-Vienne",
  "FR-88"=>"Vosges",
  "FR-89"=>"Yonne",
  "FR-90"=>"Territoire de Belfort",
  "FR-91"=>"Essonne",
  "FR-92"=>"Hauts-de-Seine",
  "FR-93"=>"Seine-Saint-Denis",
  "FR-94"=>"Val-de-Marne",
  "FR-95', "Val-d'Oise"),
  "FR-NC"=>"New Caledonia",
  "FR-PF"=>"French Polynesia",
  "FR-PM"=>"Saint-Pierre and Miquelon",
  "FR-TF"=>"French Southern Territories",
  "FR-YT"=>"Mayotte",
  "FR-WF"=>"Wallis and Futuna",
);

$this->gabon_regions = array(
  "1"=>"Estuaire",
  "2"=>"Haut-Ogooue",
  "3"=>"Moyen-Ogooue",
  "4"=>"Ngounie",
  "5"=>"Nyanga",
  "6"=>"Ogooue-Ivindo",
  "7"=>"OgoouE-Lolo",
  "8"=>"Ogooue-Maritime",
  "9"=>"Woleu-Ntem",
);

$this->georgia_regions = array(
  "AB"=>"Abkhazia",
  "AJ"=>"Ajaria",
  "GU"=>"Guria",
  "IM', "Imeret'i"),
  "KA', "Kakhet'i"),
  "KK', "K'vemo K'art'li"),
  "MM', "Mts'khet'a-Mt'ianet'i"),
  "RL', "Racha-Lech'khumi-K'vemo"),
  "SZ', "Samegrelo-Zemo Svanet'i"),
  "SJ', "Samts'khe-Javakhet'i"),
  "SK', "Shida K'art'li"),
  "TB', "T'bilisi"),
);

$this->germany_regions = array(
  "BAW"=>"Baden-Württemberg",
  "BAY"=>"Bayern",
  "BER"=>"Berlin",
  "BRG"=>"Brandenburg",
  "BRE"=>"Bremen",
  "HAM"=>"Hamburg",
  "HES"=>"Hessen",
  "MEC"=>"Mecklenburg-Vorpommern",
  "NDS"=>"Niedersachsen",
  "NRW"=>"Nordrhein-Westfalen",
  "RHE"=>"Rheinland-Pfalz",
  "SAR"=>"Saarland",
  "SAS"=>"Sachsen",
  "SAC"=>"Sachsen-Anhalt",
  "SCN"=>"Schleswig-Holstein",
  "THE"=>"Thüringen",
);

$this->ghana_regions = array(
  "GH-AH"=>"Ashanti",
  "GH-BA"=>"Brong-Ahafo",
  "GH-CP"=>"Central",
  "GH-EP"=>"Eastern",
  "GH-AA"=>"Greater Accra",
  "GH-NP"=>"Northern",
  "GH-UE"=>"Upper East",
  "GH-UW"=>"Upper West",
  "GH-TV"=>"Volta",
  "GH-WP"=>"Western",
);

$this->greece_regions = array(
  "ATT"=>"Αττική",
  "AIT"=>"Αιτωλοακαρνανία",
  "ARG"=>"Αργολίδα",
  "ARK"=>"Αρκαδία",
  "ART"=>"Άρτα",
  "AHA"=>"Αχαϊα",
  "BOI"=>"Βοιωτία",
  "GRE"=>"Γρεβενά",
  "DRA"=>"Δράμα",
  "DOD"=>"Δωδεκάνησα",
  "EVR"=>"Έβρος",
  "EVI"=>"Εύβοια",
  "EVT"=>"Ευρυτανία",
  "ZAK"=>"Ζάκυνθος",
  "ILI"=>"Ηλεία",
  "HMA"=>"Ημαθία",
  "HRA"=>"Ηράκλειο",
  "THP"=>"Θεσπρωτία",
  "THE"=>"Θεσσαλονίκη",
  "IOA"=>"Ιωάννινα",
  "KAV"=>"Καβάλα",
  "KAR"=>"Καρδίτσα",
  "KAS"=>"Καστοριά",
  "KER"=>"Κέρκυρα",
  "KEF"=>"Κεφαλληνία",
  "KIL"=>"Κιλκίς",
  "KOZ"=>"Κοζάνη",
  "KOR"=>"Κορινθία",
  "KYK"=>"Κυκλάδες",
  "LAK"=>"Λακωνία",
  "LAR"=>"Λάρισα",
  "LAS"=>"Λασίθι",
  "LES"=>"Λέσβος",
  "LEF"=>"Λευκάδα",
  "MAG"=>"Μαγνησία",
  "ΜES"=>"Μεσσηνία",
  "XAN"=>"Ξάνθη",
  "PEL"=>"Πέλλα",
  "PIE"=>"Πιερία",
  "PRE"=>"Πρέβεζα",
  "RET"=>"Ρέθυμνο",
  "ROD"=>"Ροδόπη",
  "SAM"=>"Σάμος",
  "SER"=>"Σέρρες",
  "TRI"=>"Τρίκαλα",
  "FTH"=>"Φθιώτιδα",
  "FLO"=>"Φλώρινα",
  "FOK"=>"Φωκίδα",
  "HAL"=>"Χαλκιδική",
  "HAN"=>"Χανιά",
  "HIO"=>"Χίος",
);

$this->greenland_regions = array(
  "NK"=>"Nuuk",
  "NQ"=>"Nuussuaq",
  "KQ"=>"Kangerlussuaq",
  "ST"=>"Sisimiut",
  "MQ"=>"Maniitsoq",
  "TQ"=>"Tasiilaq",
  "KK"=>"Kulusuk",
  "AP"=>"Alluitsup Paa",
  "QQ"=>"Qaqortoq",
  "NA"=>"Narsaq",
  "NK"=>"Nanortalik",
  "NR"=>"Narsarsuaq",
  "IQ"=>"Ikerasassuaq",
  "KT"=>"Kangilinnguit",
  "AK"=>"Arsuk",
  "PT"=>"Paamiut",
  "AT"=>"Aasiaat",
  "QT"=>"Qasigiannguit",
  "IL"=>"Ilulissat",
  "QE"=>"Qeqertarsuaq",
  "KA"=>"Kangaatsiaq",
  "UM"=>"Uummannaq",
  "UP"=>"Upernavik",
  "QA"=>"Qaarsut",
  "PT"=>"Pituffik",
  "QN"=>"Qaanaaq",
  "SN"=>"Station Nord",
  "IT"=>"Ittoqqortoormiit",
  "MV"=>"Mestersvig",
  "DH"=>"Danmarkshavn",
  "CP"=>"Constable Pynt",
  "SS"=>"Slædepatruljen Sirius",
);

$this->guatemala_regions = array(
  "AV"=>"Alta Verapaz",
  "BV"=>"Baja Verapaz",
  "CM"=>"Chimaltenango",
  "CQ"=>"Chiquimula",
  "PR"=>"El Progreso",
  "ES"=>"Escuintla",
  "GU"=>"Guatemala",
  "HU"=>"Huehuetenango",
  "IZ"=>"Izabal",
  "JA"=>"Jalapa",
  "JU"=>"Jutiapa",
  "PE"=>"Peten",
  "QZ"=>"Quetzaltenango",
  "QC"=>"Quiche",
  "RE"=>"Retalhuleu",
  "SA"=>"Sacatepequez",
  "SM"=>"San Marcos",
  "SR"=>"Santa Rosa",
  "SO"=>"Solola",
  "SU"=>"Suchitepequez",
  "TO"=>"Totonicapan",
  "ZA"=>"Zacapa",
);

$this->guinea_regions = array(
  "GN-BE"=>"Beyla",
  "GN-BF"=>"Boffa",
  "GN-BK"=>"Boké",
  "GN-CO"=>"Coyah",
  "GN-DB"=>"Dabola",
  "GN-DL"=>"Dalaba",
  "GN-DI"=>"Dinguiraye",
  "GN-DU"=>"Dubréka",
  "GN-FA"=>"Faranah",
  "GN-FO"=>"Forécariah",
  "GN-FR"=>"Fria",
  "GN-GA"=>"Gaoual",
  "GN-GU"=>"Guékédou",
  "GN-KA"=>"Kankan",
  "GN-KE"=>"Kérouané",
  "GN-KD"=>"Kindia",
  "GN-KS"=>"Kissidougou",
  "GN-KB"=>"Koubia",
  "GN-KN"=>"Koundara",
  "GN-KO"=>"Kouroussa",
  "GN-LA"=>"Labé",
  "GN-LE"=>"Lélouma",
  "GN-LO"=>"Lola",
  "GN-MC"=>"Macenta",
  "GN-ML"=>"Mali",
  "GN-MM"=>"Mamou",
  "GN-MD"=>"Mandiana",
  "GN-NZ"=>"Nzérékor",
  "GN-PI"=>"Pita",
  "GN-SI"=>"Siguiri",
  "GN-TE"=>"Télimélé",
  "GN-TO"=>"Tougué",
  "GN-YO"=>"Yomou",
);

$this->guinea_bissau_regions = array(
  "GW-BS"=>"Bissau",
  "GW-BA"=>"Bafatá",
  "GW-BM"=>"Biombo",
  "GW-BL"=>"Bolama",
  "GW-CA"=>"Cacheu",
  "GW-GA"=>"Gabú",
  "GW-OI"=>"Oio",
  "GW-QU"=>"Quinara",
  "GW-TO"=>"Tombali",
);

$this->guyana_regions = array(
  "GY-BA"=>"Barima-Waini",
  "GY-CU"=>"Cuyuni-Mazaruni",
  "GY-DE"=>"Demerara-Mahaica",
  "GY-EB"=>"East Berbice-Corentyne",
  "GY-ES"=>"Essequibo Islands-West Demerara",
  "GY-MA"=>"Mahaica-Berbice",
  "GY-PM"=>"Pomeroon-Supenaam",
  "GY-PT"=>"Potaro-Siparuni",
  "GY-UD"=>"Upper Demerara-Berbice",
  "GY-UT"=>"Upper Takutu-Upper Essequibo",
);

$this->haiti_regions = array(
  "HT-AR"=>"Artibonite",
  "HT-CE"=>"Centre",
  "HT-GA"=>"Grande-Anse",
  "HT-NI"=>"Nippes",
  "HT-ND"=>"Nord",
  "HT-NE"=>"Nord-Est",
  "HT-NO"=>"Nord-Ouest",
  "HT-OU"=>"Ouest",
  "HT-SD"=>"Sud",
  "HT-SE"=>"Sud-Est",
);

$this->honduras_regions = array(
  "HN-AT"=>"Atlántida",
  "HN-CL"=>"Colón",
  "HN-CM"=>"Comayagua",
  "HN-CP"=>"Copán",
  "HN-CR"=>"Cortés",
  "HN-CH"=>"Choluteca",
  "HN-EP"=>"El Paraíso",
  "HN-FM"=>"Francisco Morazán",
  "HN-GD"=>"Gracias a Dios",
  "HN-IN"=>"Intibucá",
  "HN-IB"=>"Islas de la Bahía",
  "HN-LP"=>"La Paz",
  "HN-LE"=>"Lempira",
  "HN-OC"=>"Ocotepeque",
  "HN-OL"=>"Olancho",
  "HN-SB"=>"Santa Bárbara",
  "HN-VA"=>"Valle",
  "HN-YO"=>"Yoro",
);

$this->hong_kong_regions = array(
  "HK"=>"Hong Kong",
  "NT"=>"New Territories",
);

$this->hungary_regions = array(
  "BUD"=>"Budapest",
  "BAR"=>"Baranya",
  "BKK"=>"Bács-Kiskun",
  "BÉK"=>"Békés",
  "BAZ"=>"Borsod-Abaúj-Zemplén",
  "CSO"=>"Csongrád",
  "FEJ"=>"Fejér",
  "GYS"=>"Gyõr-Sopron",
  "HAB"=>"Hajdú-Bihar",
  "HEV"=>"Heves",
  "JNS"=>"Jász-Nagykun-Szolnok",
  "KOE"=>"Komárom-Esztergom",
  "NOG"=>"Nógrád",
  "PES"=>"Pest",
  "SOM"=>"Somogy",
  "SSB"=>"Szabolcs-Szatmár-Bereg",
  "TOL"=>"Tolna",
  "VAS"=>"Vas",
  "VES"=>"Veszprém",
  "ZAL"=>"Zala",
);

$this->iceland_regions = array(
  "IS-7"=>"Austurland",
  "IS-1"=>"Höfuðborgarsvæði utan Reykjavíkur",
  "IS-6"=>"Norðurland eystra",
  "IS-5"=>"Norðurland vestra",
  "IS-0"=>"Reykjavík",
  "IS-8"=>"Suðurland",
  "IS-2"=>"Suðurnes",
  "IS-4"=>"Vestfirðir",
  "IS-3"=>"Vesturland",
);

$this->india_regions = array(
  "AN"=>"Andaman and Nicobar",
  "AP"=>"Andhra Pradesh",
  "AR"=>"Arunachal Pradesh",
  "AS"=>"Assam",
  "BR"=>"Bihar",
  "CH"=>"Chandigarh",
  "CT"=>"Chhattisgarh",
  "DN"=>"Dadra and Nagar Haveli",
  "DD"=>"Daman and Diu",
  "DL"=>"Delhi",
  "GA"=>"Goa",
  "GJ"=>"Gujarat",
  "HR"=>"Haryana",
  "HP"=>"Himachal Pradesh",
  "JK"=>"Jammu and Kashmir",
  "JH"=>"Jharkhand",
  "KA"=>"Karnataka",
  "KL"=>"Kerala",
  "LD"=>"Lakshadweep",
  "MP"=>"Madhya Pradesh",
  "MH"=>"Maharashtra",
  "MN"=>"Manipur",
  "ML"=>"Meghalaya",
  "MZ"=>"Mizoram",
  "NL"=>"Nagaland",
  "OR"=>"Orissa",
  "PY"=>"Puducherry",
  "PB"=>"Punjab",
  "RJ"=>"Rajasthan",
  "SK"=>"Sikkim",
  "TN"=>"Tamil Nadu",
  "TR"=>"Tripura",
  "UL"=>"Uttarakhand",
  "UP"=>"Uttar Pradesh",
  "WB"=>"West Bengal",
);

$this->indonesia_regions = array(
  "NAD"=>"Nanggroe Aceh Darussalam",
  "Sumut"=>"Sumatera Utara",
  "Sumbar"=>"Sumatera Barat",
  "Riau"=>"Riau",
  "Jambi"=>"Jambi",
  "Sumsel"=>"Sumatera Selatan",
  "Bengkulu"=>"Bengkulu",
  "Lampung"=>"Lampung",
  "Babel"=>"Kepulauan Bangka Belitung",
  "Kepri"=>"Kepulauan Riau",
  "DKI"=>"DKI Jakarta",
  "Jabar"=>"Jawa Barat",
  "Jateng"=>"Jawa Tengah",
  "DIY"=>"Daista Yogyakarta",
  "Jatim"=>"Jawa Timur",
  "Banten"=>"Banten",
  "Bali"=>"Bali",
  "NTB"=>"Nusa Tenggara Barat",
  "NTT"=>"Nusa Tenggara Timur",
  "Kalbar"=>"Kalimantan Barat",
  "Kalteng"=>"Kalimantan Tengah",
  "Kalsel"=>"Kalimantan Selatan",
  "Kaltim"=>"Kalimantan Timur",
  "Sulut"=>"Sulawesi Utara",
  "Sulteng"=>"Sulawesi Tengah",
  "Sulsel"=>"Sulawesi Selatan",
  "Sultra"=>"Sulawesi Tenggara",
  "Gorontalo"=>"Gorontalo",
  "Sulbar"=>"Sulawesi Barat",
  "Maluku"=>"Maluku",
  "Malut"=>"Maluku Utara",
  "Papua"=>"Papua",
  "Irjabar"=>"Irian Jaya Barat",
);

$this->iran_regions = array(
  "AS"=>"آذربایجان شرقی",
  "AG"=>"آذربایجان غربی",
  "AR"=>"اردبیل",
  "ES"=>"اصفهان",
  "IL"=>"ایلام",
  "BU"=>"بوشهر",
  "TH"=>"تهران",
  "CB"=>"چهار محال بختیاری",
  "KH"=>"خراسان جنوبی",
  "KH"=>"خراسان رضوی",
  "KH"=>"خراسان شمالی",
  "KZ"=>"خوزستان",
  "ZN"=>"زنجان",
  "SB"=>"سیستان و بلوچستان",
  "SM"=>"سمنان",
  "FR"=>"فارس",
  "QZ"=>"قزوین",
  "QM"=>"قم",
  "KD"=>"کردستان",
  "KR"=>"کرمان",
  "KS"=>"کرمانشاه",
  "KB"=>"کهگیلویه و بویر احمد",
  "GL"=>"گیلان",
  "GS"=>"گلستان",
  "LR"=>"لرستان",
  "MZ"=>"مازندران",
  "MR"=>"مرکزی",
  "HR"=>"هرمزگان",
  "HM"=>"همدان",
  "YZ"=>"یزد",
);

$this->iraq_regions = array(
  "IQ-AN"=>"Al Anbār",
  "IQ-BA"=>"Al Başrah",
  "IQ-MU"=>"Al Muthanná",
  "IQ-QA"=>"Al Qādisīyah",
  "IQ-NA"=>"An Najaf",
  "IQ-AR"=>"Arbīl",
  "IQ-SU"=>"As Sulaymānīyah",
  "IQ-TS', "At Ta'mīm"),
  "IQ-BB"=>"Babil !Bābil",
  "IQ-BG"=>"Baghdād",
  "IQ-DA"=>"Dahūk",
  "IQ-DQ"=>"Dhī Qār",
  "IQ-DI"=>"Diyālá",
  "IQ-KA', "Karbalā'"),
  "IQ-MA"=>"Maysān",
  "IQ-NI"=>"Nīnawá",
  "IQ-SD"=>"Şalāḩ ad Dīn",
  "IQ-WA"=>"Wāsiţ",
);

$this->ireland_regions = array(
  "CARLOW"=>"Co. Carlow",
  "CAVAN"=>"Co. Cavan",
  "CLARE"=>"Co. Clare",
  "CORK"=>"Co. Cork",
  "DONEGAL"=>"Co. Donegal",
  "DUBLIN"=>"Co. Dublin",
  "GALWAY"=>"Co. Galway",
  "KERRY"=>"Co. Kerry",
  "KILDARE"=>"Co. Kildare",
  "KILKENNY"=>"Co. Kilkenny",
  "LAOIS"=>"Co. Laois",
  "LEITRIM"=>"Co. Leitrim",
  "LIMERICK"=>"Co. Limerick",
  "LONGFORD"=>"Co. Longford",
  "LOUTH"=>"Co. Louth",
  "MAYO"=>"Co. Mayo",
  "MEATH"=>"Co. Meath",
  "MONAGHAN"=>"Co. Monaghan",
  "OFFALY"=>"Co. Offaly",
  "ROSCOMMON"=>"Co. Roscommon",
  "SLIGO"=>"Co. Sligo",
  "TIPPERARY"=>"Co. Tipperary",
  "WATERFORD"=>"Co. Waterford",
  "WESTMEATH"=>"Co. Westmeath",
  "WEXFORD"=>"Co. Wexford",
  "WICKLOW"=>"Co. Wicklow",
);

$this->israel_regions = array(
  "BS', "Be'er Sheva"),
  "BH', "Bika'at Hayarden"),
  "EA"=>"Eilat and Arava",
  "GA"=>"Galil",
  "HA"=>"Haifa",
  "JM"=>"Jehuda Mountains",
  "JE"=>"Jerusalem",
  "NE"=>"Negev",
  "SE"=>"Semaria",
  "SH"=>"Sharon",
  "TA"=>"Tel Aviv (Gosh Dan)",
);

$this->italy_regions = array(
  "AG"=>"Agrigento",
  "AL"=>"Alessandria",
  "AN"=>"Ancona",
  "AO"=>"Aosta",
  "AP"=>"Ascoli Piceno",
  "AQ', "L'Aquila"),
  "AR"=>"Arezzo",
  "AT"=>"Asti",
  "AV"=>"Avellino",
  "BA"=>"Bari",
  "BG"=>"Bergamo",
  "BI"=>"Biella",
  "BL"=>"Belluno",
  "BN"=>"Benevento",
  "BO"=>"Bologna",
  "BR"=>"Brindisi",
  "BS"=>"Brescia",
  "BT"=>"Barletta-Andria-Trani",
  "BZ"=>"Bolzano",
  "CA"=>"Cagliari",
  "CB"=>"Campobasso",
  "CE"=>"Caserta",
  "CH"=>"Chieti",
  "CI"=>"Carbonia-Iglesias",
  "CL"=>"Caltanissetta",
  "CN"=>"Cuneo",
  "CO"=>"Como",
  "CR"=>"Cremona",
  "CS"=>"Cosenza",
  "CT"=>"Catania",
  "CZ"=>"Catanzaro",
  "EN"=>"Enna",
  "FC"=>"Forlì-Cesena",
  "FE"=>"Ferrara",
  "FG"=>"Foggia",
  "FI"=>"Firenze",
  "FM"=>"Fermo",
  "FR"=>"Frosinone",
  "GE"=>"Genova",
  "GO"=>"Gorizia",
  "GR"=>"Grosseto",
  "IM"=>"Imperia",
  "IS"=>"Isernia",
  "KR"=>"Crotone",
  "LC"=>"Lecco",
  "LE"=>"Lecce",
  "LI"=>"Livorno",
  "LO"=>"Lodi",
  "LT"=>"Latina",
  "LU"=>"Lucca",
  "MB"=>"Monza e Brianza",
  "MC"=>"Macerata",
  "ME"=>"Messina",
  "MI"=>"Milano",
  "MN"=>"Mantova",
  "MO"=>"Modena",
  "MS"=>"Massa e Carrara",
  "MT"=>"Matera",
  "NA"=>"Napoli",
  "NO"=>"Novara",
  "NU"=>"Nuoro",
  "OG"=>"Ogliastra",
  "OR"=>"Oristano",
  "OT"=>"Olbia-Tempio",
  "PA"=>"Palermo",
  "PC"=>"Piacenza",
  "PD"=>"Padova",
  "PE"=>"Pescara",
  "PG"=>"Perugia",
  "PI"=>"Pisa",
  "PN"=>"Pordenone",
  "PO"=>"Prato",
  "PR"=>"Parma",
  "PU"=>"Pesaro e Urbino",
  "PT"=>"Pistoia",
  "PV"=>"Pavia",
  "PZ"=>"Potenza",
  "RA"=>"Ravenna",
  "RC"=>"Reggio Calabria",
  "RE"=>"Reggio Emilia",
  "RG"=>"Ragusa",
  "RI"=>"Rieti",
  "RM"=>"Roma",
  "RN"=>"Rimini",
  "RO"=>"Rovigo",
  "SA"=>"Salerno",
  "SI"=>"Siena",
  "SO"=>"Sondrio",
  "SP"=>"La Spezia",
  "SR"=>"Siracusa",
  "SS"=>"Sassari",
  "SV"=>"Savona",
  "TA"=>"Taranto",
  "TE"=>"Teramo",
  "TN"=>"Trento",
  "TO"=>"Torino",
  "TP"=>"Trapani",
  "TR"=>"Terni",
  "TS"=>"Trieste",
  "TV"=>"Treviso",
  "UD"=>"Udine",
  "VA"=>"Varese",
  "VB"=>"Verbano-Cusio-Ossola",
  "VC"=>"Vercelli",
  "VE"=>"Venezia",
  "VI"=>"Vicenza",
  "VR"=>"Verona",
  "VS"=>"Medio Campidano",
  "VT"=>"Viterbo",
  "VV"=>"Vibo Valentia",
  "RSM"=>"Rep San Marino",
  "CTV"=>"Città del Vaticano",
);

$this->jamaica_regions = array(
  "JM-13"=>"Clarendon",
  "JM-09"=>"Hanover",
  "JM-01"=>"Kingston",
  "JM-12"=>"Manchester",
  "JM-04"=>"Portland",
  "JM-02"=>"Saint Andrew",
  "JM-06"=>"Saint Ann",
  "JM-14"=>"Saint Catherine",
  "JM-11"=>"Saint Elizabeth",
  "JM-08"=>"Saint James",
  "JM-05"=>"Saint Mary",
  "JM-03"=>"Saint Thomas",
  "JM-07"=>"Trelawny",
  "JM-10"=>"Westmoreland",
);

$this->japan_regions = array(
  "01"=>"北海道",
  "02"=>"青森県",
  "03"=>"岩手県",
  "04"=>"宮城県",
  "05"=>"秋田県",
  "06"=>"山形県",
  "07"=>"福島県",
  "08"=>"茨城県",
  "09"=>"栃木県",
  "10"=>"群馬県",
  "11"=>"埼玉県",
  "12"=>"千葉県",
  "13"=>"東京都",
  "14"=>"神奈川県",
  "15"=>"新潟県",
  "16"=>"富山県",
  "17"=>"石川県",
  "18"=>"福井県",
  "19"=>"山梨県",
  "20"=>"長野県",
  "21"=>"岐阜県",
  "22"=>"静岡県",
  "23"=>"愛知県",
  "24"=>"三重県",
  "25"=>"滋賀県",
  "26"=>"京都府",
  "27"=>"大阪府",
  "28"=>"兵庫県",
  "29"=>"奈良県",
  "30"=>"和歌山県",
  "31"=>"鳥取県",
  "32"=>"島根県",
  "33"=>"岡山県",
  "34"=>"広島県",
  "35"=>"山口県",
  "36"=>"徳島県",
  "37"=>"香川県",
  "38"=>"愛媛県",
  "39"=>"高知県",
  "40"=>"福岡県",
  "41"=>"佐賀県",
  "42"=>"長崎県",
  "43"=>"熊本県",
  "44"=>"大分県",
  "45"=>"宮崎県",
  "46"=>"鹿児島県",
  "47"=>"沖縄県",
);

$this->jorda_regions = array(
  "JO-AJ', "'Ajlūn"),
  "JO-AQ', "Al 'Aqaba"),
  "JO-BA', "Al Balqā'"),
  "JO-KA"=>"Al Karak",
  "JO-MA"=>"Al Mafraq",
  "JO-AM', "'Ammān"),
  "JO-AT"=>"Aţ Ţafīlah",
  "JO-AZ', "Az Zarqā'"),
  "JO-IR"=>"Irbid",
  "JO-JA"=>"Jarash",
  "JO-MN', "Ma'ٰān"),
  "JO-MD"=>"Mādaba",
);

$this->kazakhstan_regions = array(
  "ALA"=>"Алматы",
  "TSE"=>"Астана",
  "AKM"=>"Акмолинская область",
  "AKT"=>"Актюбинская область",
  "ALM"=>"Алматинская область",
  "ATR"=>"Атырауская область",
  "EKZ"=>"Восточно-Казахстанская область",
  "DZH"=>"Жамбылская область",
  "WKZ"=>"Западно-Казахстанская область",
  "KAR"=>"Карагандинская область",
  "KOR"=>"Кызылординская область",
  "KUS"=>"Костанайская область",
  "MAN"=>"Мангистауская область",
  "PVL"=>"Павлодарская область",
  "NKZ"=>"Северо-Казахстанская область",
  "SKZ"=>"Южно-Казахстанская область",
);

$this->kenya_regions = array(
  "700"=>"Bonde la Ufa",
  "200"=>"Central",
  "300"=>"Coast",
  "400"=>"Eastern",
  "500"=>"Kaskazini Masariki",
  "200"=>"Kati",
  "800"=>"Maqharibi",
  "400"=>"Mashariki",
  "110"=>"Nairobi",
  "500"=>"North-Eastern",
  "600"=>"Nyanza",
  "300"=>"Pwani",
  "700"=>"Rift Valley",
  "800"=>"Western",
);

$this->kiribati_regions = array(
  "KI-G"=>"Gilbert Islands",
  "KI-L"=>"Line Islands",
  "KI-P"=>"Phoenix Islands",
);

$this->korea_democratic_peoples_republic_regions = array(
  "KP-01"=>"P’yŏngyang",
  "KP-13"=>"Nasŏn (Najin-Sŏnbong",
  "KP-02"=>"P’yŏngan-namdo",
  "KP-03"=>"P’yŏngan-bukto",
  "KP-04"=>"Chagang-do",
  "KP-05"=>"Hwanghae-namdo",
  "KP-06"=>"Hwanghae-bukto",
  "KP-07"=>"Kangwŏn-do",
  "KP-08"=>"Hamgyŏng-namdo",
  "KP-09"=>"Hamgyŏng-bukto",
  "KP-10"=>"Yanggang-do",
);

$this->korea_republic_regions = array(
  "CO', "Ch'ungch'ong-bukto"),
  "CH', "Ch'ungch'ong-namdo"),
  "CD"=>"Cheju-do",
  "CB"=>"Cholla-bukto",
  "CN"=>"Cholla-namdo",
  "IG', "Inch'on-gwangyoksi"),
  "KA"=>"Kangwon-do",
  "KG"=>"Kwangju-gwangyoksi",
  "KD"=>"Kyonggi-do",
  "KB"=>"Kyongsang-bukto",
  "KN"=>"Kyongsang-namdo",
  "PG"=>"Pusan-gwangyoksi",
  "SO', "Soul-t'ukpyolsi"),
  "TA"=>"Taegu-gwangyoksi",
  "TG"=>"Taejon-gwangyoksi",
);

$this->kuwait_regions = array(
  "KW-AH"=>"Al Aḩmadi",
  "KW-FA"=>"Al Farwānīyah",
  "KW-JA"=>"Al Jahrah",
  "KW-KU"=>"Al Kuwayt",
  "KW-HA"=>"Hawallī !Ḩawallī",
  "KW-MU"=>"Mubārak al Kabīr",
);

$this->kyrgyzstan_regions = array(
  "KG-GB"=>"Bishkek",
  "KG-B"=>"Batken",
  "KG-C"=>"Chü",
  "KG-J"=>"Jalal-Abad",
  "KG-N"=>"Naryn",
  "KG-O"=>"Osh",
  "KG-T"=>"Talas",
  "KG-Y"=>"Ysyk-Köl",
);

$this->laos_regions = array(
  "LA-VT"=>"Vientiane",
  "LA-AT"=>"Attapu [Attopeu]",
  "LA-BK"=>"Bokè",
  "LA-BL"=>"Bolikhamxai [Borikhane]",
  "LA-CH"=>"Champasak [Champassak]",
  "LA-HO"=>"Houaphan",
  "LA-KH"=>"Khammouan",
  "LA-LM"=>"Louang Namtha",
  "LA-LP"=>"Louangphabang [Louang Prabang]",
  "LA-OU"=>"Oudômxai [Oudomsai]",
  "LA-PH"=>"Phôngsali [Phong Saly]",
  "LA-SL"=>"Salavan [Saravane]",
  "LA-SV"=>"Savannakhé",
  "LA-VI"=>"Vientiane",
  "LA-XA"=>"Xaignabouli",
  "LA-XE"=>"Xekong",
  "LA-XI"=>"Xiangkhoang [Xieng Khouang]",
  "LA-XN"=>"Xaisômbou",
);

$this->latvia_regions = array(
  "AI"=>"Aizkraukles rajons",
  "AL"=>"Alūksnes rajons",
  "BL"=>"Balvu rajons",
  "BU"=>"Bauskas rajons",
  "CE"=>"Cēsu rajons",
  "DGV"=>"Daugavpils pilsēta",
  "DA"=>"Daugavpils rajons",
  "DO"=>"Dobeles rajons",
  "GU"=>"Gulbenes rajons",
  "JK"=>"Jēkabpils rajons",
  "JEL"=>"Jelgavas pilsēta",
  "JL"=>"Jelgavas rajons",
  "JUR"=>"Jūrmalas pilsēta",
  "KR"=>"Krāslavas rajons",
  "KU"=>"Kuldīgas rajons",
  "LPX"=>"Liepājas pilsēta",
  "LE"=>"Liepājas rajons",
  "LM"=>"Limbažu rajons",
  "LU"=>"Ludzas rajons",
  "MA"=>"Madonas rajons",
  "OG"=>"Ogres rajons",
  "PR"=>"Preiļu rajons",
  "REZ"=>"Rēzeknes pilsēta",
  "RE"=>"Rēzeknes rajons",
  "RIX"=>"Rīgas pilsēta",
  "RI"=>"Rīgas rajons",
  "SA"=>"Saldus rajons",
  "TA"=>"Talsu rajons",
  "TU"=>"Tukuma rajons",
  "VK"=>"Valkas rajons",
  "VM"=>"Valmieras rajons",
  "VEN"=>"Ventspils pilsēta",
  "VE"=>"Ventspils rajons",
);

$this->lebanon_regions = array(
  "LB-AK"=>"Aakkâr",
  "LB-BH"=>"Baalbek-Hermel",
  "LB-BI"=>"Beqaa",
  "LB-BA"=>"Beyrouth",
  "LB-AS"=>"Liban-Nord",
  "LB-JA"=>"Liban-Sud",
  "LB-JL"=>"Mont-Liban",
  "LB-NA"=>"Nabatîyé",
);

$this->lesotho_regions = array(
  "LS-D"=>"Berea",
  "LS-B"=>"Butha-Buthe",
  "LS-C"=>"Leribe",
  "LS-E"=>"Mafeteng",
  "LS-A"=>"Maseru",
  "LS-F', "Mohale's Hoek"),
  "LS-J"=>"Mokhotlong",
  "LS-H', "Qacha's Nek"),
  "LS-G"=>"Quthing",
  "LS-K"=>"Thaba-Tseka",
);

$this->liberia_regions = array(
  "LR-BM"=>"Bomi",
  "LR-BG"=>"Bong",
  "LR-GP"=>"Gbarpolu",
  "LR-GB"=>"Grand Bassa",
  "LR-CM"=>"Grand Cape Mount",
  "LR-GG"=>"Grand Gedeh",
  "LR-GK"=>"Grand Kru",
  "LR-LO"=>"Lofa",
  "LR-MG"=>"Margibi",
  "LR-MY"=>"Maryland",
  "LR-MO"=>"Montserrado",
  "LR-NI"=>"Nimba",
  "LR-RI"=>"Rivercess",
  "LR-RG"=>"RiverGee",
  "LR-SI"=>"Sinoe",
);

$this->libya_regions = array(
  "LY-BU"=>"Al Buţnān",
  "LY-JA"=>"Al Jabal al Akhḑar",
  "LY-JG"=>"Al Jabal al Gharbī",
  "LY-JI"=>"Al Jifārah",
  "LY-JU"=>"Al Jufrah",
  "LY-KF"=>"Al Kufrah",
  "LY-MJ"=>"Al Marj",
  "LY-MB"=>"Al Marqab",
  "LY-WA"=>"Al Wāḩāt",
  "LY-NQ"=>"An Nuqaţ al Khams",
  "LY-ZA"=>"Az Zāwiyah",
  "LY-BA"=>"Banghāzī",
  "LY-DR"=>"Darnah",
  "LY-GT"=>"Ghāt",
  "LY-MI"=>"Mişrātah",
  "LY-MQ"=>"Murzuq",
  "LY-NL"=>"Nālūt",
  "LY-SB"=>"Sabhā",
  "LY-SR"=>"Surt",
  "LY-TB"=>"Tarābulus",
  "LY-WD"=>"Wādī al Ḩayāt",
  "LY-WS"=>"Wādī ash Shāţiʾ",
);

$this->liechtenstein_regions = array(
  "LI-01"=>"Balzers",
  "LI-02"=>"Eschen",
  "LI-03"=>"Gamprin",
  "LI-04"=>"Mauren",
  "LI-05"=>"Planken",
  "LI-06"=>"Ruggell",
  "LI-07"=>"Schaan",
  "LI-08"=>"Schellenberg",
  "LI-09"=>"Triesen",
  "LI-10"=>"Triesenberg",
  "LI-11"=>"Vaduz",
);

$this->lithuania_regions = array(
  "AK"=>"Akmenės rajonas",
  "AL"=>"Alytaus rajonas",
  "AN"=>"Anykščių rajonas",
  "BIR"=>"Biržų rajonas",
  "IG"=>"Ignalinos rajonas",
  "JON"=>"Jonavos rajonas",
  "JO"=>"Joniškio rajonas",
  "JUR"=>"Jurbarko rajonas",
  "KAI"=>"Kaišiadorių rajonas",
  "KA"=>"Kauno rajonas",
  "KE"=>"Kėdainių rajonas",
  "KEL"=>"Kelmės rajonas",
  "KLA"=>"Klaipėdos rajonas",
  "KR"=>"Kretingos rajonas",
  "KU"=>"Kupiškio rajonas",
  "LA"=>"Lazdijų rajonas",
  "MA"=>"Mažeikių rajonas",
  "MO"=>"Molėtų rajonas",
  "PA"=>"Pakruojo rajonas",
  "PAN"=>"Panevėžio rajonas",
  "PAS"=>"Pasvalio rajonas",
  "PLU"=>"Plungės rajonas",
  "PR"=>"Prienų rajonas",
  "RA"=>"Radviliškio rajonas",
  "RAS"=>"Raseinių rajonas",
  "RO"=>"Rokiškio rajonas",
  "SK"=>"Skuodo rajonas",
  "SA"=>"Šakių rajonas",
  "SAL"=>"Šalčininkų rajonas",
  "SIA"=>"Šiaulių rajonas",
  "SI"=>"Šilalės rajonas",
  "SIL"=>"Šilutės rajonas",
  "SIR"=>"Širvintų rajonas",
  "SV"=>"Švenčionių rajonas",
  "TA"=>"Tauragės rajonas",
  "TE"=>"Telšių rajonas",
  "TR"=>"Trakų rajonas",
  "UK"=>"Ukmergės rajonas",
  "UT"=>"Utenos rajonas",
  "VA"=>"Varėnos rajonas",
  "VI"=>"Vilkaviškio rajonas",
  "VIL"=>"Vilniaus rajonas",
  "ZAR"=>"Zarasų rajonas",
);

//European Union Member countries in ISO 3166-1 alpha-2. Used for shipping and tax calculations
$this->eu_countries = array(
  'AT',
  'BE',
  'BG',
  'CY',
  'CZ',
  'DK',
  'EE',
  'FI',
  'FR',
  'DE',
  'GB',
  'GR',
  'HU',
  'IE',
  'IT',
  'LV',
  'LT',
  'LU',
  'MT',
  'NL',
  'PL',
  'PT',
  'RO',
  'SK',
  'SI',
  'ES',
  'SE'
);

//currency list - http://www.xe.com/symbols.php
//last perameter is symbol which is unicode hex: http://www.mikezilla.com/exp0012.html
$this->currencies = array(
  "ALL"=> array("Albania, Leke", "4c, 65, 6b"),
  "AFN"=> array("Afghanistan, Afghanis", "60b"),
  "ARS"=> array("Argentina, Pesos", "24"),
  "AWG"=> array("Aruba, Guilders (also called Florins)", "192"),
  "AUD"=> array("Australia, Dollars", "24"),
  "AZN"=> array("Azerbaijan, New Manats", "43c, 430, 43d"),
  "BSD"=> array("Bahamas, Dollars", "24"),
  "BBD"=> array("Barbados, Dollars", "24"),
  "BYR"=> array("Belarus, Rubles", "70, 2e"),
  "BZD"=> array("Belize, Dollars", "42, 5a, 24"),
  "BMD"=> array("Bermuda, Dollars", "24"),
  "BOB"=> array("Bolivia, Bolivianos", "24, 62"),
  "BAM"=> array("Bosnia and Herzegovina, Convertible Marka", "4b, 4d"),
  "BWP"=> array("Botswana, Pulas", "50"),
  "BGN"=> array("Bulgaria, Leva", "43b, 432"),
  "BRL"=> array("Brazil, Reais", "52, 24"),
  "BND"=> array("Brunei Darussalam, Dollars", "24"),
  "KHR"=> array("Cambodia, Riels", "17db"),
  "CAD"=> array("Canada, Dollars", "24"),
  "KYD"=> array("Cayman Islands, Dollars", "24"),
  "CLP"=> array("Chile, Pesos", "24"),
  "CNY"=> array("China, Yuan Renminbi", "a5"),
  "COP"=> array("Colombia, Pesos", "24"),
  "CRC"=> array("Costa Rica, Colon", "20a1"),
  "HRK"=> array("Croatia, Kuna", "6b, 6e"),
  "CUP"=> array("Cuba, Pesos", "20b1"),
  "CZK"=> array("Czech Republic, Koruny", "4b, 10d"),
  "DKK"=> array("Denmark, Kroner", "6b, 72"),
  "DOP"=> array("Dominican Republic, Pesos", "52, 44, 24"),
  "XCD"=> array("East Caribbean, Dollars", "24"),
  "EGP"=> array("Egypt, Pounds", "a3"),
  "SVC"=> array("El Salvador, Colones", "24"),
  "EEK"=> array("Estonia, Krooni", "6b, 72"),
  "EUR"=> array("Euro", "20ac"),
  "FKP"=> array("Falkland Islands, Pounds", "a3"),
  "FJD"=> array("Fiji, Dollars", "24"),
  "GEL"=> array("Georgia, lari", "6c, 61, 72, 69"),
  "GHC"=> array("Ghana, Cedis", "a2"),
  "GIP"=> array("Gibraltar, Pounds", "a3"),
  "GTQ"=> array("Guatemala, Quetzales", "51"),
  "GGP"=> array("Guernsey, Pounds", "a3"),
  "GYD"=> array("Guyana, Dollars", "24"),
  "HNL"=> array("Honduras, Lempiras", "4c"),
  "HKD"=> array("Hong Kong, Dollars", "24"),
  "HUF"=> array("Hungary, Forint", "46, 74"),
  "ISK"=> array("Iceland, Kronur", "6b, 72"),
  "INR"=> array("India, Rupees", "20a8"),
  "IDR"=> array("Indonesia, Rupiahs", "52, 70"),
  "IRR"=> array("Iran, Rials", "fdfc"),
  "IMP"=> array("Isle of Man, Pounds", "a3"),
  "ILS"=> array("Israel, New Shekels", "20aa"),
  "JMD"=> array("Jamaica, Dollars", "4a, 24"),
  "JPY"=> array("Japan, Yen", "a5"),
  "JEP"=> array("Jersey, Pounds", "a3"),
  "KZT"=> array("Kazakhstan, Tenge", "43b, 432"),
  "KES"=> array("Kenyan Shilling", "4B, 73, 68, 73"),
  "KWD"=> array("Kuwait, dinar", "4B, 2E, 44, 2E"),
  "KGS"=> array("Kyrgyzstan, Soms", "43b, 432"),
  "LAK"=> array("Laos, Kips", "20ad"),
  "LVL"=> array("Latvia, Lati", "4c, 73"),
  "LBP"=> array("Lebanon, Pounds", "a3"),
  "LRD"=> array("Liberia, Dollars", "24"),
  "LTL"=> array("Lithuania, Litai", "4c, 74"),
  "MKD"=> array("Macedonia, Denars", "434, 435, 43d"),
  "MYR"=> array("Malaysia, Ringgits", "52, 4d"),
  "MUR"=> array("Mauritius, Rupees", "20a8"),
  "MXN"=> array("Mexico, Pesos", "24"),
  "MNT"=> array("Mongolia, Tugriks", "20ae"),
  "MAD"=> array("Morocco, dirhams", "64, 68"),
  "MZN"=> array("Mozambique, Meticais", "4d, 54"),
  "NAD"=> array("Namibia, Dollars", "24"),
  "NPR"=> array("Nepal, Rupees", "20a8"),
  "ANG"=> array("Netherlands Antilles, Guilders (also called Florins)", "192"),
  "NZD"=> array("New Zealand, Dollars", "24"),
  "NIO"=> array("Nicaragua, Cordobas", "43, 24"),
  "NGN"=> array("Nigeria, Nairas", "20a6"),
  "KPW"=> array("North Korea, Won", "20a9"),
  "NOK"=> array("Norway, Krone", "6b, 72"),
  "OMR"=> array("Oman, Rials", "fdfc"),
  "PKR"=> array("Pakistan, Rupees", "20a8"),
  "PAB"=> array("Panama, Balboa", "42, 2f, 2e"),
  "PYG"=> array("Paraguay, Guarani", "47, 73"),
  "PEN"=> array("Peru, Nuevos Soles", "53, 2f, 2e"),
  "PHP"=> array("Philippines, Pesos", "50, 68, 70"),
  "PLN"=> array("Poland, Zlotych", "7a, 142"),
  "QAR"=> array("Qatar, Rials", "fdfc"),
  "RON"=> array("Romania, New Lei", "6c, 65, 69"),
  "RUB"=> array("Russia, Rubles", "440, 443, 431"),
  "SHP"=> array("Saint Helena, Pounds", "a3"),
  "SAR"=> array("Saudi Arabia, Riyals", "fdfc"),
  "RSD"=> array("Serbia, Dinars", "414, 438, 43d, 2e"),
  "SCR"=> array("Seychelles, Rupees", "20a8"),
  "SGD"=> array("Singapore, Dollars", "24"),
  "SBD"=> array("Solomon Islands, Dollars", "24"),
  "SOS"=> array("Somalia, Shillings", "53"),
  "ZAR"=> array("South Africa, Rand", "52"),
  "KRW"=> array("South Korea, Won", "20a9"),
  "LKR"=> array("Sri Lanka, Rupees", "20a8"),
  "SEK"=> array("Sweden, Kronor", "6b, 72"),
  "CHF"=> array("Switzerland, Francs", "43, 48, 46"),
  "SRD"=> array("Suriname, Dollars", "24"),
  "SYP"=> array("Syria, Pounds", "a3"),
  "TWD"=> array("Taiwan, New Dollars", "4e, 54, 24"),
  "THB"=> array("Thailand, Baht", "e3f"),
  "TTD"=> array("Trinidad and Tobago, Dollars", "54, 54, 24"),
  "TRY"=> array("Turkey, Lira", "54, 4c"),
  "TRL"=> array("Turkey, Liras", "20a4"),
  "TVD"=> array("Tuvalu, Dollars", "24"),
  "UAH"=> array("Ukraine, Hryvnia", "20b4"),
  "AED"=> array("United Arab Emirates, dirhams", "64, 68"),
  "GBP"=> array("United Kingdom, Pounds", "a3"),
  "USD"=> array("United States of America, Dollars", "24"),
  "UYU"=> array("Uruguay, Pesos", "24, 55"),
  "UZS"=> array("Uzbekistan, Sums", "43b, 432"),
  "VEF"=> array("Venezuela, Bolivares Fuertes", "42, 73"),
  "VND"=> array("Vietnam, Dong", "20ab"),
  "XAF"=> array("BEAC, CFA Francs", "46, 43, 46, 41"),
  "XOF"=> array("BCEAO, CFA Francs", "46, 43, 46, 41"),
  "YER"=> array("Yemen, Rials", "fdfc"),
  "ZWD"=> array("Zimbabwe, Zimbabwe Dollars", "5a, 24"),
	"POINTS"=> array("Points (for point based stores)", "50, 6f, 69, 6e, 74, 73"),
	"CREDITS"=> array("Credits (for credit based stores)", "43, 72, 65, 64, 69, 74, 73")
);

?>
