<?php
/*
MarketPress Data Structures
*/

//country list
$this->countries = array(
  "AF" => "Afghanistan",
  "AL" => "Albania",
  "DZ" => "Algeria",
  "AS" => "American Samoa",
  "AD" => "Andorra",
  "AO" => "Angola",
  "AI" => "Anguilla",
  "AQ" => "Antarctica",
  "AG" => "Antigua And Barbuda",
  "AR" => "Argentina",
  "AM" => "Armenia",
  "AW" => "Aruba",
  "AU" => "Australia",
  "AT" => "Austria",
  "AZ" => "Azerbaijan",
  "BS" => "Bahamas",
  "BH" => "Bahrain",
  "BD" => "Bangladesh",
  "BB" => "Barbados",
  "BY" => "Belarus",
  "BE" => "Belgium",
  "BZ" => "Belize",
  "BJ" => "Benin",
  "BM" => "Bermuda",
  "BT" => "Bhutan",
  "BO" => "Bolivia",
  "BA" => "Bosnia And Herzegowina",
  "BW" => "Botswana",
  "BV" => "Bouvet Island",
  "BR" => "Brazil",
  "IO" => "British Indian Ocean Territory",
  "BN" => "Brunei Darussalam",
  "BG" => "Bulgaria",
  "BF" => "Burkina Faso",
  "BI" => "Burundi",
  "KH" => "Cambodia",
  "CM" => "Cameroon",
  "CA" => "Canada",
  "CV" => "Cape Verde",
  "KY" => "Cayman Islands",
  "CF" => "Central African Republic",
  "TD" => "Chad",
  "CL" => "Chile",
  "CN" => "China",
  "CX" => "Christmas Island",
  "CC" => "Cocos (Keeling) Islands",
  "CO" => "Colombia",
  "KM" => "Comoros",
  "CG" => "Congo",
  "CD" => "Congo, The Democratic Republic Of The",
  "CK" => "Cook Islands",
  "CR" => "Costa Rica",
  "CI" => "Cote D'Ivoire",
  "HR" => "Croatia (Local Name: Hrvatska)",
  "CU" => "Cuba",
  "CY" => "Cyprus",
  "CZ" => "Czech Republic",
  "DK" => "Denmark",
  "DJ" => "Djibouti",
  "DM" => "Dominica",
  "DO" => "Dominican Republic",
  "TP" => "East Timor",
  "EC" => "Ecuador",
  "EG" => "Egypt",
  "SV" => "El Salvador",
  "GQ" => "Equatorial Guinea",
  "ER" => "Eritrea",
  "EE" => "Estonia",
  "ET" => "Ethiopia",
  "FK" => "Falkland Islands (Malvinas)",
  "FO" => "Faroe Islands",
  "FJ" => "Fiji",
  "FI" => "Finland",
  "FR" => "France",
  "FX" => "France, Metropolitan",
  "GF" => "French Guiana",
  "PF" => "French Polynesia",
  "TF" => "French Southern Territories",
  "GA" => "Gabon",
  "GM" => "Gambia",
  "GE" => "Georgia",
  "DE" => "Germany",
  "GH" => "Ghana",
  "GI" => "Gibraltar",
  "GR" => "Greece",
  "GL" => "Greenland",
  "GD" => "Grenada",
  "GP" => "Guadeloupe",
  "GU" => "Guam",
  "GT" => "Guatemala",
  "GN" => "Guinea",
  "GW" => "Guinea-Bissau",
  "GY" => "Guyana",
  "HT" => "Haiti",
  "HM" => "Heard And Mc Donald Islands",
  "VA" => "Holy See (Vatican City State)",
  "HN" => "Honduras",
  "HK" => "Hong Kong",
  "HU" => "Hungary",
  "IS" => "Iceland",
  "IN" => "India",
  "ID" => "Indonesia",
  "IR" => "Iran (Islamic Republic Of)",
  "IQ" => "Iraq",
  "IE" => "Ireland",
  "IL" => "Israel",
  "IT" => "Italy",
  "JM" => "Jamaica",
  "JP" => "Japan",
  "JO" => "Jordan",
  "KZ" => "Kazakhstan",
  "KE" => "Kenya",
  "KI" => "Kiribati",
  "KP" => "Korea, Democratic People's Republic Of",
  "KR" => "Korea, Republic Of",
  "KW" => "Kuwait",
  "KG" => "Kyrgyzstan",
  "LA" => "Lao People's Democratic Republic",
  "LV" => "Latvia",
  "LB" => "Lebanon",
  "LS" => "Lesotho",
  "LR" => "Liberia",
  "LY" => "Libyan Arab Jamahiriya",
  "LI" => "Liechtenstein",
  "LT" => "Lithuania",
  "LU" => "Luxembourg",
  "MO" => "Macau",
  "MK" => "Macedonia, Former Yugoslav Republic Of",
  "MG" => "Madagascar",
  "MW" => "Malawi",
  "MY" => "Malaysia",
  "MV" => "Maldives",
  "ML" => "Mali",
  "MT" => "Malta",
  "MH" => "Marshall Islands",
  "MQ" => "Martinique",
  "MR" => "Mauritania",
  "MU" => "Mauritius",
  "YT" => "Mayotte",
  "MX" => "Mexico",
  "FM" => "Micronesia, Federated States Of",
  "MD" => "Moldova, Republic Of",
  "MC" => "Monaco",
  "MN" => "Mongolia",
  "MS" => "Montserrat",
  "MA" => "Morocco",
  "MZ" => "Mozambique",
  "MM" => "Myanmar",
  "NA" => "Namibia",
  "NR" => "Nauru",
  "NP" => "Nepal",
  "NL" => "Netherlands",
  "AN" => "Netherlands Antilles",
  "NC" => "New Caledonia",
  "NZ" => "New Zealand",
  "NI" => "Nicaragua",
  "NE" => "Niger",
  "NG" => "Nigeria",
  "NU" => "Niue",
  "NF" => "Norfolk Island",
  "MP" => "Northern Mariana Islands",
  "NO" => "Norway",
  "OM" => "Oman",
  "PK" => "Pakistan",
  "PW" => "Palau",
  "PA" => "Panama",
  "PG" => "Papua New Guinea",
  "PY" => "Paraguay",
  "PE" => "Peru",
  "PH" => "Philippines",
  "PN" => "Pitcairn",
  "PL" => "Poland",
  "PT" => "Portugal",
  "PR" => "Puerto Rico",
  "QA" => "Qatar",
  "RE" => "Reunion",
  "RO" => "Romania",
  "RU" => "Russian Federation",
  "RW" => "Rwanda",
  "KN" => "Saint Kitts And Nevis",
  "LC" => "Saint Lucia",
  "VC" => "Saint Vincent And The Grenadines",
  "WS" => "Samoa",
  "SM" => "San Marino",
  "ST" => "Sao Tome And Principe",
  "SA" => "Saudi Arabia",
  "SN" => "Senegal",
  "SC" => "Seychelles",
  "SL" => "Sierra Leone",
  "SG" => "Singapore",
  "SK" => "Slovakia (Slovak Republic)",
  "SI" => "Slovenia",
  "SB" => "Solomon Islands",
  "SO" => "Somalia",
  "ZA" => "South Africa",
  "GS" => "South Georgia, South Sandwich Islands",
  "ES" => "Spain",
  "LK" => "Sri Lanka",
  "SH" => "St. Helena",
  "PM" => "St. Pierre And Miquelon",
  "SD" => "Sudan",
  "SR" => "Suriname",
  "SJ" => "Svalbard And Jan Mayen Islands",
  "SZ" => "Swaziland",
  "SE" => "Sweden",
  "CH" => "Switzerland",
  "SY" => "Syrian Arab Republic",
  "TW" => "Taiwan",
  "TJ" => "Tajikistan",
  "TZ" => "Tanzania, United Republic Of",
  "TH" => "Thailand",
  "TG" => "Togo",
  "TK" => "Tokelau",
  "TO" => "Tonga",
  "TT" => "Trinidad And Tobago",
  "TN" => "Tunisia",
  "TR" => "Turkey",
  "TM" => "Turkmenistan",
  "TC" => "Turks And Caicos Islands",
  "TV" => "Tuvalu",
  "UG" => "Uganda",
  "UA" => "Ukraine",
  "AE" => "United Arab Emirates",
  "GB" => "United Kingdom",
  "US" => "United States",
  "UM" => "United States Minor Outlying Islands",
  "UY" => "Uruguay",
  "UZ" => "Uzbekistan",
  "VU" => "Vanuatu",
  "VE" => "Venezuela",
  "VN" => "Viet Nam",
  "VG" => "Virgin Islands (British)",
  "VI" => "Virgin Islands (U.S.)",
  "WF" => "Wallis And Futuna Islands",
  "EH" => "Western Sahara",
  "YE" => "Yemen",
  "YU" => "Yugoslavia",
  "ZM" => "Zambia",
  "ZW" => "Zimbabwe"
);

//USA states list
$this->usa_states = array(
  'AL'=>"Alabama",
	'AK'=>"Alaska",
	'AZ'=>"Arizona",
	'AR'=>"Arkansas",
	'CA'=>"California",
	'CO'=>"Colorado",
	'CT'=>"Connecticut",
	'DE'=>"Delaware",
	'DC'=>"District Of Columbia",
	'FL'=>"Florida",
	'GA'=>"Georgia",
	'HI'=>"Hawaii",
	'ID'=>"Idaho",
	'IL'=>"Illinois",
	'IN'=>"Indiana",
	'IA'=>"Iowa",
	'KS'=>"Kansas",
	'KY'=>"Kentucky",
	'LA'=>"Louisiana",
	'ME'=>"Maine",
	'MD'=>"Maryland",
	'MA'=>"Massachusetts",
	'MI'=>"Michigan",
	'MN'=>"Minnesota",
	'MS'=>"Mississippi",
	'MO'=>"Missouri",
	'MT'=>"Montana",
	'NE'=>"Nebraska",
	'NV'=>"Nevada",
	'NH'=>"New Hampshire",
	'NJ'=>"New Jersey",
	'NM'=>"New Mexico",
	'NY'=>"New York",
	'NC'=>"North Carolina",
	'ND'=>"North Dakota",
	'OH'=>"Ohio",
	'OK'=>"Oklahoma",
	'OR'=>"Oregon",
	'PA'=>"Pennsylvania",
	'RI'=>"Rhode Island",
	'SC'=>"South Carolina",
	'SD'=>"South Dakota",
	'TN'=>"Tennessee",
	'TX'=>"Texas",
	'UT'=>"Utah",
	'VT'=>"Vermont",
	'VA'=>"Virginia",
	'WA'=>"Washington",
	'WV'=>"West Virginia",
	'WI'=>"Wisconsin",
	'WY'=>"Wyoming"
);

//UK counties/provinces
$this->uk_counties = array("Aberdeenshire"=>"Aberdeenshire","Angus/Forfarshire"=>"Angus/Forfarshire","Argyllshire"=>"Argyllshire",
"Ayrshire"=>"Ayrshire","Banffshire"=>"Banffshire","Bedfordshire"=>"Bedfordshire","Berkshire"=>"Berkshire",
"Berwickshire"=>"Berwickshire","Blaenau Gwent"=>"Blaenau Gwent","Bridgend"=>"Bridgend",
"Buckinghamshire"=>"Buckinghamshire","Buteshire"=>"Buteshire","Caerphilly"=>"Caerphilly","Caithness"=>"Caithness",
"Cambridgeshire"=>"Cambridgeshire","Cardiff"=>"Cardiff","Carmarthenshire"=>"Carmarthenshire",
"Ceredigion"=>"Ceredigion","Cheshire"=>"Cheshire","Clackmannanshire"=>"Clackmannanshire",
"Conwy"=>"Conwy","Cornwall"=>"Cornwall","Cromartyshire"=>"Cromartyshire","Cumbria"=>"Cumbria",
"Denbighshire"=>"Denbighshire","Derbyshire"=>"Derbyshire","Devon"=>"Devon","Dorset"=>"Dorset",
"Dumfriesshire"=>"Dumfriesshire","Dunbartonshire/Dumbartonshire"=>"Dunbartonshire/Dumbartonshire",
"Durham"=>"Durham","East Lothian/Haddingtonshire"=>"East Lothian/Haddingtonshire","Essex"=>"Essex","Fife"=>"Fife",
"Flintshire"=>"Flintshire","Gloucestershire"=>"Gloucestershire","Greater London"=>"Greater London","Greater Manchester"=>"Greater Manchester","Gwynedd"=>"Gwynedd","Hampshire"=>"Hampshire",
"Herefordshire"=>"Herefordshire","Hertfordshire"=>"Hertfordshire","Huntingdonshire"=>"Huntingdonshire",
"Inverness-shire"=>"Inverness-shire","Isle of Anglesey"=>"Isle of Anglesey","Kent"=>"Kent",
"Kincardineshire"=>"Kincardineshire","Kinross-shire"=>"Kinross-shire","Kirkcudbrightshire"=>"Kirkcudbrightshire",
"Lanarkshire"=>"Lanarkshire","Lancashire"=>"Lancashire","Leicestershire"=>"Leicestershire",
"Lincolnshire"=>"Lincolnshire","Merthyr Tydfil"=>"Merthyr Tydfil","Middlesex"=>"Middlesex",
"Midlothian/Edinburghshire"=>"Midlothian/Edinburghshire","Monmouthshire"=>"Monmouthshire",
"Morayshire"=>"Morayshire","Nairnshire"=>"Nairnshire","Neath Port Talbot"=>"Neath Port Talbot",
"Newport"=>"Newport","Norfolk"=>"Norfolk","Northamptonshire"=>"Northamptonshire",
"Northumberland"=>"Northumberland","Nottinghamshire"=>"Nottinghamshire","Orkney"=>"Orkney",
"Oxfordshire"=>"Oxfordshire","Peeblesshire"=>"Peeblesshire","Pembrokeshire"=>"Pembrokeshire",
"Perthshire"=>"Perthshire","Powys"=>"Powys","Renfrewshire"=>"Renfrewshire",
"Rhondda Cynon Taff"=>"Rhondda Cynon Taff","Ross-shire"=>"Ross-shire","Roxburghshire"=>"Roxburghshire",
"Rutland"=>"Rutland","Selkirkshire"=>"Selkirkshire","Shetland"=>"Shetland","Shropshire"=>"Shropshire",
"Somerset"=>"Somerset","Staffordshire"=>"Staffordshire","Stirlingshire"=>"Stirlingshire","Suffolk"=>"Suffolk",
"Surrey"=>"Surrey","Sussex"=>"Sussex","Sutherland"=>"Sutherland","Swansea"=>"Swansea","Torfaen"=>"Torfaen",
"Vale of Glamorgan"=>"Vale of Glamorgan","Warwickshire"=>"Warwickshire",
"West Lothian/Linlithgowshire"=>"West Lothian/Linlithgowshire","Westmorland"=>"Westmorland",
"Wigtownshire"=>"Wigtownshire","Wiltshire"=>"Wiltshire",
"Worcestershire"=>"Worcestershire","Wrexham"=>"Wrexham","Yorkshire"=>"Yorkshire");

//Australian states
$this->australian_states = array(
  "NSW"=>"New South Wales",
  "VIC"=>"Victoria",
  "QLD"=>"Queensland",
  "TAS"=>"Tasmania",
  "SA"=>"South Australia",
  "WA"=>"Western Australia",
  "NT"=>"Northern Territory",
  "ACT"=>"Australian Capital Territory"
);

//Canadian provinces
$this->canadian_provinces = array(
  "BC"=>"British Columbia",
  "ON"=>"Ontario",
  "NL"=>"Newfoundland and Labrador",
  "NS"=>"Nova Scotia",
  "PE"=>"Prince Edward Island",
  "NB"=>"New Brunswick",
  "QC"=>"Quebec",
  "MB"=>"Manitoba",
  "SK"=>"Saskatchewan",
  "AB"=>"Alberta",
  "NT"=>"Northwest Territories",
  "NU"=>"Nunavut",
  "YT"=>"Yukon Territory"
);

$this->afganistan_regions = array(
  "BDS"=>"Badakhshan",
  "BDG"=>"Badghis",
  "BGL"=>"Baghlan",
  "BAL"=>"Balkh",
  "BAM"=>"Bamian",
  "FRA"=>"Farah",
  "FYB"=>"Faryab",
  "GHA"=>"Ghazni",
  "GHO"=>"Ghowr",
  "HEL"=>"Helmand",
  "HER"=>"Herat",
  "JOW"=>"Jowzjan",
  "KAB"=>"Kabul",
  "KAN"=>"Kandahar",
  "KAP"=>"Kapisa",
  "KHO"=>"Khost",
  "KNR"=>"Konar",
  "KDZ"=>"Kondoz",
  "LAG"=>"Laghman",
  "LOW"=>"Lowgar",
  "NAN"=>"Nangrahar",
  "NIM"=>"Nimruz",
  "NUR"=>"Nurestan",
  "ORU"=>"Oruzgan",
  "PIA"=>"Paktia",
  "PKA"=>"Paktika",
  "PAR"=>"Parwan",
  "SAM"=>"Samangan",
  "SAR"=>"Sar-e Pol",
  "TAK"=>"Takhar",
  "WAR"=>"Wardak",
  "ZAB"=>"Zabol",
);

$this->albania_regions = array(
  "1"=>"Berat county",
  "2"=>"Durres county",
  "3"=>"Elbasan county",
  "4"=>"Fier county",
  "5"=>"Gjirokaster county",
  "6"=>"Korce county",
  "7"=>"Kukes county",
  "8"=>"Lezhe county",
  "9"=>"Diber county",
  "10"=>"Shkoder county",
  "11"=>"Tirane county",
  "12"=>"Vlore county",
);

$this->algeria_region = array(
  "ADRAR"=>"Adrar",
  "AIN TEMOUCHENT"=>"Ain Temouchent",
  "ALGIERS"=>"Algiers",
  "ANNABA"=>"Annaba",
  "LAGHOUAT"=>"Laghouat",
  "BATNA"=>"Batna",
  "BEJAIA"=>"Bejaia",
  "BISKRA"=>"Biskra",
  "BECHAR"=>"Bechar",
  "BLIDA"=>"Blida",
  "BOUIRA"=>"Bouira",
  "CHLEF"=>"Chlef",
  "CONSTANTINE"=>"Constantine",
  "DJELFA"=>"Djelfa",
  "TAMANGHASSET"=>"Tamanghasset",
  "TEBESSA"=>"Tebessa",
  "TLEMCEN"=>"Tlemcen",
  "TIZI OUZOU"=>"Tizi Ouzou",
  "JIJEL"=>"Jijel",
  "SETIF"=>"Setif",
  "SAIDA"=>"Saida",
  "SKIKDA"=>"Skikda",
  "SIDI BEL ABBES"=>"Sidi Bel Abbes",
  "GUELMA"=>"Guelma",
  "MEDEA"=>"Medea",
  "MOSTAGANEM"=>"Mostaganem",
  "MSILA"=>"MSila",
  "ORAN"=>"Oran",
  "OUARGLA"=>"Ouargla",
  "OUM EL-BOUAGHI"=>"Oum el-Bouaghi",
  "EL BAYADH"=>"El Bayadh",
  "ILLIZI"=>"Illizi",
  "BORDJ BOU ARRERIDJ"=>"Bordj Bou Arreridj",
  "BOUMERDES"=>"Boumerdes",
  "EL TARF"=>"El Tarf",
  "TINDDOUF"=>"Tindouf",
  "TISSEMSILT"=>"Tissemsilt",
  "EL OUED"=>"El Oued",
  "KHENCHELA"=>"Khenchela",
  "SOUK AHRAS"=>"Souk Ahras",
  "MILA"=>"Mila",
  "AIN DEFLA"=>"Ain Defla",
  "NAAMA"=>"Naama",
  "GHARDAIA"=>"Ghardaia",
  "RELIZANE"=>"Relizane",
);

$this->andorra_regions = array(
  "CA"=>"Canillo",
  "EN"=>"Encamp",
  "MA"=>"La Massana",
  "OR"=>"Ordino",
  "JL"=>"Sant Julià de Lòria",
  "AN"=>"Andorra La Vella",
  "EE"=>"Escaldes Engordany",
);

$this->angola_regions = array(
  "BGO"=>"Bengo",
  "BGU"=>"Benguela",
  "BIE"=>"Bie",
  "CAB"=>"Cabinda",
  "CCU"=>"Cuando Cubango",
  "CNO"=>"Cuanza Norte",
  "CUS"=>"Cuanza Sul",
  "CNN"=>"Cunene",
  "HUA"=>"Huambo",
  "HUI"=>"Huila",
  "LUA"=>"Luanda",
  "LNO"=>"Lunda Norte",
  "LSU"=>"Lunda Sul",
  "MAL"=>"Malanje",
  "MOX"=>"Moxico",
  "NAM"=>"Namibe",
  "UIG"=>"Uige",
  "ZAI"=>"Zaire",
);

$this->anguilla_regions = array(
  "BP"=>"Blowing Point",
  "EE"=>"East End",
  "GH"=>"George Hill",
  "IH"=>"Island Harbour",
  "NH"=>"North Hill",
  "NS"=>"North Side",
  "SG"=>"Sandy Ground",
  "SH"=>"Sandy Hill",
  "SO"=>"South Hill",
  "ST"=>"Stoney Ground",
  "TF"=>"The Farrington",
  "TQ"=>"The Quarter (including Rey Hill)",
  "TV"=>"The Valley (including Upper & South Valley)",
  "WE"=>"West End (including Long Bay)",
);

$this->antigua_barbuda_regions = array(
  "GE"=>"St. George",
  "JO"=>"St. John",
  "MA"=>"St. Mary",
  "PA"=>"St. Paul",
  "PE"=>"St. Peter",
  "BB"=>"Barbuda",
  "RD"=>"Redonda",
  "PH"=>"St. Philip",
);

$this->argentina_regions = array(
  "A"=>"Salta",
  "B"=>"Buenos Aires Province",
  "C"=>"Capital Federal",
  "D"=>"San Luis",
  "E"=>"Entre Ríos",
  "F"=>"La Rioja",
  "G"=>"Santiago del Estero",
  "H"=>"Chaco",
  "J"=>"San Juan",
  "K"=>"Catamarca",
  "L"=>"La Pampa",
  "M"=>"Mendoza",
  "N"=>"Misiones",
  "P"=>"Formosa",
  "Q"=>"Neuquén",
  "R"=>"Río Negro",
  "S"=>"Santa Fe",
  "T"=>"Tucumán",
  "U"=>"Chubut",
  "V"=>"Tierra del Fuego",
  "W"=>"Corrientes",
  "X"=>"Córdoba",
  "Y"=>"Jujuy",
  "Z"=>"Santa Cruz",
);

$this->armenia_regions = array(
  "AG"=>"Araqacotn",
  "AR"=>"Ararat",
  "AV"=>"Armavir",
  "ER"=>"Erevan",
  "GR"=>"Geqarkunik",
  "KT"=>"Kotayk",
  "LO"=>"Lory",
  "SH"=>"Sirak",
  "SU"=>"Syunik",
  "TV"=>"Tavus",
  "VD"=>"Vayoc Jor",
);

$this->austria_regions = array(
  "BUR"=>"Burgenland",
  "KAR"=>"Kärnten",
  "NOS"=>"Niederöesterreich",
  "OOS"=>"Oberöesterreich",
  "SAL"=>"Salzburg",
  "STE"=>"Steiermark",
  "TIR"=>"Tirol",
  "VOR"=>"Vorarlberg",
  "WIE"=>"Wien",
  );

$this->ajerbaijan_regions = array(
  "ABS"=>"Absheron",
  "AGM"=>"Aghdam",
  "AGS"=>"Aghdash",
  "AGC"=>"Aghjabedi",
  "AGA"=>"Aghstafa",
  "AGU"=>"Aghsu",
  "AB"=>"Ali-Bairamly",
  "AST"=>"Astara",
  "BAB"=>"Babek",
  "BA"=>"Baku",
  "BAL"=>"Balaken",
  "BAR"=>"Barda",
  "BEY"=>"Beilagan",
  "BIL"=>"Bilasuvar",
  "DAS"=>"Dashkesan",
  "DAV"=>"Devechi",
  "FUZ"=>"Fizuli",
  "QAB"=>"Gabala",
  "GAD"=>"Gadabey",
  "QAX"=>"Gakh",
  "GA"=>"Ganja",
  "QAZ"=>"Gazakh",
  "GOR"=>"Geranboy",
  "QOB"=>"Gobustan",
  "GOY"=>"Goychay",
  "QBA"=>"Guba",
  "QBI"=>"Gubadly",
  "QUS"=>"Gusar",
  "HAC"=>"Hacuqabul",
  "IMI"=>"Imishli",
  "ISM"=>"Ismailly",
  "CAL"=>"Jalilabad",
  "CAB"=>"Jebrail",
  "CUL"=>"Julfa",
  "KAL"=>"Kelbajar",
  "XAC"=>"Khachmaz",
  "XA"=>"Khankendy",
  "XAN"=>"Khanlar",
  "XCI"=>"Khojaly",
  "XVD"=>"Khojavend",
  "XIZ"=>"Khyzy",
  "KUR"=>"Kyurdamir",
  "LAC"=>"Lachin",
  "LAN"=>"Lankaran district",
  "LA"=>"Lankaran city",
  "LER"=>"Lerik",
  "MAS"=>"Masally",
  "MI"=>"Mingechevir",
  "NA"=>"Naftalan",
  "NX"=>"Nakhchivan",
  "NEF"=>"Neftchala",
  "OGU"=>"Oghuz",
  "ORD"=>"Ordubad",
  "SAT"=>"Saatly",
  "SAB"=>"Sabirabad",
  "SAL"=>"Salyan",
  "SMX"=>"Samuh",
  "SAD"=>"Sedarak",
  "SAH"=>"Shahbuz",
  "SMI"=>"Shamakhy",
  "SKR"=>"Shamkir",
  "SAK"=>"Sheki district",
  "SA"=>"Sheki city",
  "SAR"=>"Sherur",
  "SUS"=>"Shusha district",
  "SS"=>"Shusha city",
  "SIY"=>"Siazan",
  "SM"=>"Sumgayit",
  "TAR"=>"Terter",
  "TOV"=>"Tovuz",
  "UCA"=>"Ujar",
  "YAR"=>"Yardymly",
  "YEV"=>"Yevlakh district",
  "YE"=>"Yevlakh city",
  "ZAQ"=>"Zagatala",
  "ZAN"=>"Zangilan",
  "ZAR"=>"Zerdab",
  );

$this->bahamas_regions = array(
  "AC"=>"Acklins and Crooked Islands",
  "BI"=>"Bimini",
  "CI"=>"Cat Island",
  "EX"=>"Exuma",
  "FP"=>"Freeport",
  "FC"=>"Fresh Creek",
  "GH', "Governor's Harbour"),
  "GT"=>"Green Turtle Cay",
  "HI"=>"Harbour Island",
  "HR"=>"High Rock",
  "IN"=>"Inaqua",
  "KB"=>"Kemps Bay",
  "LI"=>"Long Island",
  "MH"=>"Marsh Harbour",
  "MG"=>"Mayaquana",
  "NP"=>"New Providence",
  "NB"=>"Nicholls Town and Berry Islands",
  "RI"=>"Ragged Island",
  "RS"=>"Rock Sound",
  "SR"=>"San Salvador and Rum Cay",
  "SP"=>"Sandy Point",
  );

$this->bahrain_regions = array(
  "BH-13"=>"Al Manamah",
  "BH-14"=>"Al Janubiyah",
  "BH-15"=>"Al Muharraq",
  "BH-16"=>"Al Wusta",
  "BH-17"=>"Ash Shamaliyah",
  );

$this->bangladesh_regions = array(
  "1"=>"Barisal",
  "2"=>"Chittagong",
  "3"=>"Dhaka",
  "4"=>"Khulna",
  "5"=>"Rajshahi",
  "6"=>"Sylhet",
  );

$this->barbados_regions = array(
  "01"=>"Christ Church",
  "02"=>"Saint Andrew",
  "03"=>"Saint George",
  "04"=>"Saint James",
  "05"=>"Saint John",
  "06"=>"Saint Joseph",
  "07"=>"Saint Lucy",
  "08"=>"Saint Michael",
  "09"=>"Saint Peter",
  "10"=>"Saint Philip",
  "11"=>"Saint Thomas",
  );

$this->belarus_regions = array(
  "BR"=>"Brest",
  "HO"=>"Homyel",
  "HM"=>"Horad Minsk",
  "HR"=>"Hrodna",
  "MA"=>"Mahilyow",
  "MI"=>"Minsk",
  "VI"=>"Vitsyebsk",
  );

$this->belgium_regions = array(
  "VWV"=>"West-Vlaanderen",
  "VOV"=>"Oost-Vlaanderen",
  "VAN"=>"Antwerpen",
  "VLI"=>"Limburg",
  "VBR"=>"Vlaams-Brabant",
  "BRU"=>"Brussel/Bruxelles",
  "WBW"=>"Brabant-Wallon",
  "WLG"=>"Liège",
  "WHT"=>"Hainaut",
  "WNA"=>"Namur",
  "WLX"=>"Luxembourg",
  );

$this->belize_regions = array(
  "BZ"=>"Belize",
  "CY"=>"Cayo",
  "CZL"=>"Corozal",
  "OW"=>"Orange Walk",
  "SC"=>"Stann Creek",
  "TOL"=>"Toledo",
  );

$this->benin_regions = array(
  "AL"=>"Alibori",
  "AK"=>"Atacora",
  "AQ"=>"Atlantique",
  "BO"=>"Borgou",
  "CO"=>"Collines",
  "KO"=>"Couffo",
  "DO"=>"Donga",
  "LI"=>"Littoral",
  "MO"=>"Mono",
  "OU"=>"Ouémé",
  "PL"=>"Plateau",
  "ZO"=>"Zou",
  );

$this->bermuda_regions = array(
  "DEV"=>"Devonshire",
  "HAM"=>"Hamilton",
  "HA"=>"Hamilton Municipality",
  "PAG"=>"Paget",
  "PEM"=>"Pembroke",
  "SG"=>"Saint George Municipality",
  "SGE"=>"Saint Georges",
  "SAN"=>"Sandys",
  "SMI"=>"Smiths",
  "SOU"=>"Southampton",
  "WAR"=>"Warwick",
  );

$this->bhutan_regions = array(
  "GA"=>"Gasa",
  "TY"=>"Tashi Yangtse",
  "11"=>"Paro",
  "12"=>"Chhukha",
  "13"=>"Ha",
  "14"=>"Samchi",
  "15"=>"Thimphu",
  "21"=>"Chirang",
  "22"=>"Daga",
  "23"=>"Punakha",
  "24"=>"Wangdi Phodrang",
  "31"=>"Geylegphug",
  "32"=>"Tongsa",
  "33"=>"Bumthang",
  "34"=>"Shemgang",
  "41"=>"Tashigang",
  "42"=>"Mongar",
  "43"=>"Pemagatsel",
  "44"=>"Lhuntshi",
  "45"=>"Samdrup Jongkhar",
  );

$this->bolivia_regions = array(
  "BO-C"=>"Cochabamba",
  "BO-H"=>"Chuquisaca",
  "BO-B"=>"El Beni",
  "BO-L"=>"La Paz",
  "BO-O"=>"Oruro",
  "BO-N"=>"Pando",
  "BO-P"=>"Potosí",
  "BO-S"=>"Santa Cruz",
  "BO-T"=>"Tarija",
  );

$this->bosnia_herzegoniva_regions = array(
  "BIH"=>"Federacija Bosna i Hercegovina",
  "SRP"=>"Republika Srpska",
  "05"=>"Bosansko-Podrinjski Kanton",
  "10"=>"Hercegovacko-Bosanski Kanton",
  "07"=>"Hercegovacko-Neretvanski Kanton",
  "09"=>"Kanton Sarajevo",
  "02"=>"Posavski Kanton",
  "06"=>"Srednjobosanski Kanton",
  "03"=>"Tuzlanski Kanton",
  "01"=>"Unsko-Sanski Kanton",
  "08"=>"Zapadno-Hercegovacki Kanton",
  "04"=>"Zenicko-Dobojski Kanton",
  );

$this->botswana_regions = array(
  "CE"=>"Central",
  "GH"=>"Ghanzi",
  "KG"=>"Kgalagadi",
  "KL"=>"Kgatleng",
  "KW"=>"Kweneng",
  "NE"=>"North-East",
  "NW"=>"North-West",
  "SE"=>"South-East",
  "SO"=>"Southern",
  );

$this->brazil_regions = array(
  "AC"=>"Acre",
  "AL"=>"Alagoas",
  "AP"=>"Amapá",
  "AM"=>"Amazonas",
  "BA"=>"Bahia",
  "CE"=>"Ceará",
  "DF"=>"Distrito Federal",
  "ES"=>"Espírito Santo",
  "GO"=>"Goiás",
  "MA"=>"Maranhão",
  "MT"=>"Mato Grosso",
  "MS"=>"Mato Grosso do Sul",
  "MG"=>"Minas Gerais",
  "PA"=>"Pará",
  "PB"=>"Paraíba",
  "PR"=>"Paraná",
  "PE"=>"Pernambuco",
  "PI"=>"Piauí",
  "RJ"=>"Rio de Janeiro",
  "RN"=>"Rio Grande do Norte",
  "RS"=>"Rio Grande do Sul",
  "RO"=>"Rondônia",
  "RR"=>"Roraima",
  "SC"=>"Santa Catarina",
  "SP"=>"São Paulo",
  "SE"=>"Sergipe",
  "TO"=>"Tocantins",
  );

$this->brunei_darussalam_regions = array(
  "BN-BE"=>"Belait",
  "BN-BM"=>"Brunei-Muara",
  "BN-TE"=>"Temburong",
  "BN-TU"=>"Tutong",
  );

$this->burkina_faso_regions = array(
  "BAL"=>"Bale",
  "BAM"=>"Bam",
  "BAN"=>"Banwa",
  "BAZ"=>"Bazega",
  "BGR"=>"Bougouriba",
  "BLG"=>"Boulgou",
  "BLK"=>"Boulkiemde",
  "COM"=>"Comoe",
  "GAN"=>"Ganzourgou",
  "GNA"=>"Gnagna",
  "GOU"=>"Gourma",
  "HOU"=>"Houet",
  "IOB"=>"Ioba",
  "KAD"=>"Kadiogo",
  "KEN"=>"Kenedougou",
  "KMD"=>"Komandjoari",
  "KMP"=>"Kompienga",
  "KOS"=>"Kossi",
  "KOP"=>"Koulpelogo",
  "KOT"=>"Kouritenga",
  "KOW"=>"Kourweogo",
  "LER"=>"Leraba",
  "LOR"=>"Loroum",
  "MOU"=>"Mouhoun",
  "NAO"=>"Nahouri",
  "NAM"=>"Namentenga",
  "NAY"=>"Nayala",
  "NOU"=>"Noumbiel",
  "OUB"=>"Oubritenga",
  "OUD"=>"Oudalan",
  "PAS"=>"Passore",
  "PON"=>"Poni",
  "SNG"=>"Sanguie",
  "SMT"=>"Sanmatenga",
  "SEN"=>"Seno",
  "SIS"=>"Sissili",
  "SOM"=>"Soum",
  "SOR"=>"Sourou",
  "TAP"=>"Tapoa",
  "TUI"=>"Tuy",
  "YAG"=>"Yagha",
  "YAT"=>"Yatenga",
  "ZIR"=>"Ziro",
  "ZON"=>"Zondoma",
  "ZOU"=>"Zoundweogo",
  );

$this->burundi_regions = array(
  "BB"=>"Bubanza",
  "BM"=>"Bujumbura Mairie",
  "BJ"=>"Bujumbura Rural",
  "BR"=>"Bururi",
  "CA"=>"Cankuzo",
  "CI"=>"Cibitoke",
  "GI"=>"Gitega",
  "KR"=>"Karuzi",
  "KY"=>"Kayanza",
  "KI"=>"Kirundo",
  "MA"=>"Makamba",
  "MU"=>"Muramvya",
  "MY"=>"Muyinga",
  "MW"=>"Mwaro",
  "NG"=>"Ngozi",
  "RT"=>"Rutana",
  "RY"=>"Ruyigi",
  );


//European Union Member countries in ISO 3166-1 alpha-2. Used for shipping and tax calculations
$this->eu_countries = array(
  'AT',
  'BE',
  'BG',
  'CY',
  'CZ',
  'DK',
  'EE',
  'FI',
  'FR',
  'DE',
  'GB',
  'GR',
  'HU',
  'IE',
  'IT',
  'LV',
  'LT',
  'LU',
  'MT',
  'NL',
  'PL',
  'PT',
  'RO',
  'SK',
  'SI',
  'ES',
  'SE'
);

//currency list - http://www.xe.com/symbols.php
//last perameter is symbol which is unicode hex: http://www.mikezilla.com/exp0012.html
$this->currencies = array(
  "ALL"=> array("Albania, Leke", "4c, 65, 6b"),
  "AFN"=> array("Afghanistan, Afghanis", "60b"),
  "ARS"=> array("Argentina, Pesos", "24"),
  "AWG"=> array("Aruba, Guilders (also called Florins)", "192"),
  "AUD"=> array("Australia, Dollars", "24"),
  "AZN"=> array("Azerbaijan, New Manats", "43c, 430, 43d"),
  "BSD"=> array("Bahamas, Dollars", "24"),
  "BBD"=> array("Barbados, Dollars", "24"),
  "BYR"=> array("Belarus, Rubles", "70, 2e"),
  "BZD"=> array("Belize, Dollars", "42, 5a, 24"),
  "BMD"=> array("Bermuda, Dollars", "24"),
  "BOB"=> array("Bolivia, Bolivianos", "24, 62"),
  "BAM"=> array("Bosnia and Herzegovina, Convertible Marka", "4b, 4d"),
  "BWP"=> array("Botswana, Pulas", "50"),
  "BGN"=> array("Bulgaria, Leva", "43b, 432"),
  "BRL"=> array("Brazil, Reais", "52, 24"),
  "BND"=> array("Brunei Darussalam, Dollars", "24"),
  "KHR"=> array("Cambodia, Riels", "17db"),
  "CAD"=> array("Canada, Dollars", "24"),
  "KYD"=> array("Cayman Islands, Dollars", "24"),
  "CLP"=> array("Chile, Pesos", "24"),
  "CNY"=> array("China, Yuan Renminbi", "a5"),
  "COP"=> array("Colombia, Pesos", "24"),
  "CRC"=> array("Costa Rica, Colon", "20a1"),
  "HRK"=> array("Croatia, Kuna", "6b, 6e"),
  "CUP"=> array("Cuba, Pesos", "20b1"),
  "CZK"=> array("Czech Republic, Koruny", "4b, 10d"),
  "DKK"=> array("Denmark, Kroner", "6b, 72"),
  "DOP"=> array("Dominican Republic, Pesos", "52, 44, 24"),
  "XCD"=> array("East Caribbean, Dollars", "24"),
  "EGP"=> array("Egypt, Pounds", "a3"),
  "SVC"=> array("El Salvador, Colones", "24"),
  "EEK"=> array("Estonia, Krooni", "6b, 72"),
  "EUR"=> array("Euro", "20ac"),
  "FKP"=> array("Falkland Islands, Pounds", "a3"),
  "FJD"=> array("Fiji, Dollars", "24"),
  "GEL"=> array("Georgia, lari", "6c, 61, 72, 69"),
  "GHC"=> array("Ghana, Cedis", "a2"),
  "GIP"=> array("Gibraltar, Pounds", "a3"),
  "GTQ"=> array("Guatemala, Quetzales", "51"),
  "GGP"=> array("Guernsey, Pounds", "a3"),
  "GYD"=> array("Guyana, Dollars", "24"),
  "HNL"=> array("Honduras, Lempiras", "4c"),
  "HKD"=> array("Hong Kong, Dollars", "24"),
  "HUF"=> array("Hungary, Forint", "46, 74"),
  "ISK"=> array("Iceland, Kronur", "6b, 72"),
  "INR"=> array("India, Rupees", "20a8"),
  "IDR"=> array("Indonesia, Rupiahs", "52, 70"),
  "IRR"=> array("Iran, Rials", "fdfc"),
  "IMP"=> array("Isle of Man, Pounds", "a3"),
  "ILS"=> array("Israel, New Shekels", "20aa"),
  "JMD"=> array("Jamaica, Dollars", "4a, 24"),
  "JPY"=> array("Japan, Yen", "a5"),
  "JEP"=> array("Jersey, Pounds", "a3"),
  "KZT"=> array("Kazakhstan, Tenge", "43b, 432"),
  "KES"=> array("Kenyan Shilling", "4B, 73, 68, 73"),
  "KWD"=> array("Kuwait, dinar", "4B, 2E, 44, 2E"),
  "KGS"=> array("Kyrgyzstan, Soms", "43b, 432"),
  "LAK"=> array("Laos, Kips", "20ad"),
  "LVL"=> array("Latvia, Lati", "4c, 73"),
  "LBP"=> array("Lebanon, Pounds", "a3"),
  "LRD"=> array("Liberia, Dollars", "24"),
  "LTL"=> array("Lithuania, Litai", "4c, 74"),
  "MKD"=> array("Macedonia, Denars", "434, 435, 43d"),
  "MYR"=> array("Malaysia, Ringgits", "52, 4d"),
  "MUR"=> array("Mauritius, Rupees", "20a8"),
  "MXN"=> array("Mexico, Pesos", "24"),
  "MNT"=> array("Mongolia, Tugriks", "20ae"),
  "MAD"=> array("Morocco, dirhams", "64, 68"),
  "MZN"=> array("Mozambique, Meticais", "4d, 54"),
  "NAD"=> array("Namibia, Dollars", "24"),
  "NPR"=> array("Nepal, Rupees", "20a8"),
  "ANG"=> array("Netherlands Antilles, Guilders (also called Florins)", "192"),
  "NZD"=> array("New Zealand, Dollars", "24"),
  "NIO"=> array("Nicaragua, Cordobas", "43, 24"),
  "NGN"=> array("Nigeria, Nairas", "20a6"),
  "KPW"=> array("North Korea, Won", "20a9"),
  "NOK"=> array("Norway, Krone", "6b, 72"),
  "OMR"=> array("Oman, Rials", "fdfc"),
  "PKR"=> array("Pakistan, Rupees", "20a8"),
  "PAB"=> array("Panama, Balboa", "42, 2f, 2e"),
  "PYG"=> array("Paraguay, Guarani", "47, 73"),
  "PEN"=> array("Peru, Nuevos Soles", "53, 2f, 2e"),
  "PHP"=> array("Philippines, Pesos", "50, 68, 70"),
  "PLN"=> array("Poland, Zlotych", "7a, 142"),
  "QAR"=> array("Qatar, Rials", "fdfc"),
  "RON"=> array("Romania, New Lei", "6c, 65, 69"),
  "RUB"=> array("Russia, Rubles", "440, 443, 431"),
  "SHP"=> array("Saint Helena, Pounds", "a3"),
  "SAR"=> array("Saudi Arabia, Riyals", "fdfc"),
  "RSD"=> array("Serbia, Dinars", "414, 438, 43d, 2e"),
  "SCR"=> array("Seychelles, Rupees", "20a8"),
  "SGD"=> array("Singapore, Dollars", "24"),
  "SBD"=> array("Solomon Islands, Dollars", "24"),
  "SOS"=> array("Somalia, Shillings", "53"),
  "ZAR"=> array("South Africa, Rand", "52"),
  "KRW"=> array("South Korea, Won", "20a9"),
  "LKR"=> array("Sri Lanka, Rupees", "20a8"),
  "SEK"=> array("Sweden, Kronor", "6b, 72"),
  "CHF"=> array("Switzerland, Francs", "43, 48, 46"),
  "SRD"=> array("Suriname, Dollars", "24"),
  "SYP"=> array("Syria, Pounds", "a3"),
  "TWD"=> array("Taiwan, New Dollars", "4e, 54, 24"),
  "THB"=> array("Thailand, Baht", "e3f"),
  "TTD"=> array("Trinidad and Tobago, Dollars", "54, 54, 24"),
  "TRY"=> array("Turkey, Lira", "54, 4c"),
  "TRL"=> array("Turkey, Liras", "20a4"),
  "TVD"=> array("Tuvalu, Dollars", "24"),
  "UAH"=> array("Ukraine, Hryvnia", "20b4"),
  "AED"=> array("United Arab Emirates, dirhams", "64, 68"),
  "GBP"=> array("United Kingdom, Pounds", "a3"),
  "USD"=> array("United States of America, Dollars", "24"),
  "UYU"=> array("Uruguay, Pesos", "24, 55"),
  "UZS"=> array("Uzbekistan, Sums", "43b, 432"),
  "VEF"=> array("Venezuela, Bolivares Fuertes", "42, 73"),
  "VND"=> array("Vietnam, Dong", "20ab"),
  "XAF"=> array("BEAC, CFA Francs", "46, 43, 46, 41"),
  "XOF"=> array("BCEAO, CFA Francs", "46, 43, 46, 41"),
  "YER"=> array("Yemen, Rials", "fdfc"),
  "ZWD"=> array("Zimbabwe, Zimbabwe Dollars", "5a, 24"),
	"POINTS"=> array("Points (for point based stores)", "50, 6f, 69, 6e, 74, 73"),
	"CREDITS"=> array("Credits (for credit based stores)", "43, 72, 65, 64, 69, 74, 73")
);

?>
